<?php
/**
 * Dyode_curacao theme.
 *
 * Extending Magento_Checkout
 *
 * @package Dyode
 * @module  Dyode_curacao
 * @author  Rajeev K Tomy <rajeev.ktomy@dyode.com>
 * @copyright Copyright © Dyode
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Framework\View\Element\Template */
?>

<?php
$_blockId = 'icuracao_credit_card_ad';
?>
<div class="curacao-ad">
    <?= /** @escapeNotVerified */ $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId($_blockId)->toHtml() ?>
</div>