<?php
/**
 * Copyright © Dyode
 *
 */
?>
<?php
/**
 * @var $block Magento\Checkout\Block\Cart
 */
?>

<?php if ($block->getItemsSummaryQty() > 0): ?>
    <?php if ($block->getItemsSummaryQty() == 1): ?>
        <span class="bag-qty">(<?= $block->escapeHtml('1 item') ?>)</span>
    <?php else: ?>
        <span class="bag-qty">
            (<?= /* @escapeNotVerified */ $block->getItemsSummaryQty()?> <?= $block->escapeHtml( __('items')) ?>)
        </span>
    <?php endif; ?>
<?php endif; ?>

<?= $block->getChildHtml() ?>
