<form id="pricebeat" class="form" action="<?= $block->getUrl('pricebeat/user/post',['_secure' => $this->getRequest()->isSecure()]) ?>);" method="post" enctype="multipart/form-data">
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Interestbeat Form') ?></span></legend><br>
        <div class="field required">
            <label for="number" class="label"><span><?php /* @escapeNotVerified */ echo __('First name') ?></span></label>
            <div class="control">
                <input type="text" id="first_name" name="first_name" class="input-text" required="true"/>
            </div>
        </div>
        <div class="field required">
            <label for="number" class="label"><span><?php /* @escapeNotVerified */ echo __('Last-Name') ?></span></label>
            <div class="control">
                <input type="text" id="last_name" name="last_name" class="input-text"/>
            </div>
        </div>
        <div class="field required">
            <label for="email" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" id="email" name="email" class="input-text"/>
            </div>
        </div>
        <div class="field required">
            <label for="phonenumber" class="label"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
            <div class="control">
                <input type="number" id="phonenumber" name="phonenumber" class="input-text"/>
            </div>
        </div>
        <div class="field required">
            <label for="accountnumber" class="label"><span><?php /* @escapeNotVerified */ echo __('Account Number') ?></span></label>
            <div class="control">
                <input type="number" id="account_number" name="account_number" class="input-text"/>
            </div>
        </div>
        <div class="field required">
            <label for="invoicenumber" class="label"><span><?php /* @escapeNotVerified */ echo __('Invoice Number') ?></span></label>
            <div class="control">
                <input type="number" id="invoice_number" name="invoice_number" class="input-text"/>
            </div>
        </div>


            <label for="productlink" class="label"><span><?php /* @escapeNotVerified */ echo __('Product Link') ?></span></label>
            <div class="control">
                <input type="url" id="product_url" name="product_url" class="input-text"/>
            </div>


          <label for="productimage" class="label"><span><?php /* @escapeNotVerified */ echo __('Product image') ?></span></label>
          <div class="control">
            <input type="file" name="upload_file" class="input-text"/>
          </div>

    <div class="actions-toolbar">
        <div class="primary">
            <button  id="pricebeat-btn" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>

<script type="text/javascript">
require([
  'jquery'
], function($) {$(function() {
  console.log('Interestbeat js is called');
  $('#pricebeat-btn').on('click', function(e) {
    e.preventDefault();
    var productlink = $('#product_url').val();
    var product_image = $('input[name=upload_file]').val();
    console.log(productlink+" "+product_image);
    if (productlink == "" && product_image == "") {
        $('#product_url').after('<span class="error">This field is required</span>');
    } else {
      console.log('hello from else');
      $('#pricebeat').submit();

    }

  });
});
});

</script>
