<?php
    $categories = $this->getCategoryCollection();
    $categoryHelper = $this->getCategoryHelper();
?>
  <div class="content">
      <div class="gateway-fashionBeauty-section container">
          <!--Mens-Grooming-items-->
              <div class="category-widget">
                <h2><?php echo $this->getMainTitle(); ?></h2>
                   <div class="owl-carousel category-items">
                   <?php foreach($categories as $category):
                       $cat = $this->getCategorymodel($category->getId());
                       $image = $cat->getImageUrl();
                    ?>
                      <?php if($image != null): ?>
                        <div class="item single-item">
                        <a href="<?php echo $cat->getUrl(); ?>">
                        <img src="<?php echo $image; ?>" alt="<?php echo $cat->getName(); ?>" />
                       <h3><?php echo $cat->getName(); ?> </h3>
                      </div>
                    <?php endif; ?>

               <?php endforeach; ?>
             </div>
         </div>
    </div>
</div>

<script type="text/x-magento-init">
{
".category-items": {
"OwlCarousel": {
"items": 5,
"dots":false,
"loop": true,
"nav":true,
"margin": 0,
"navText": ["<div class='custom-prev'><div class='left'></div></div>", "<div class='custom-next'><div class='right'></div></div>"],
"responsive": {
"0": {
"items": 1
},
"400": {
"items": 2
},
"768": {
"items": 3
},
"1045": {
"items": 5
}
}
}
}
}
</script>
