<?php
/**
 * Dyode_curacao theme.
 *
 * Extending Magento_Catalog
 *
 * @package Dyode
 * @module  Dyode_curacao
 * @author  Rajeev K Tomy <rajeev.ktomy@dyode.com>
 * @copyright Copyright © Dyode
 */

// @codingStandardsIgnoreFile

?>
<?php
/* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Select */
$option = $block->getOption();
$isWallMountOption = (bool)($option->getIsWallMount() == 1);
$isWarrantyOption = (bool)($option->getIsWarranty() == 1);
$class = ($option->getIsRequire()) ? ' required' : '';
$class .= $isWallMountOption ? '  mount-option' : '';
$class .= $isWarrantyOption ? ' warranty-option': '';
?>

<?php if ($class==' warranty-option'): ?>
<div class="field <?= /* @escapeNotVerified */ $class ?>">
    <label class="head-label" for="select_<?= /* @escapeNotVerified */ $option->getId() ?>">
        <span><?= $block->escapeHtml($option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?= $block->getValuesHtml() ?>
        <?php if ($option->getIsRequire()): ?>
            <?php if ($option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_RADIO || $option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?= /* @escapeNotVerified */ $option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    </div>
</div>
<?php else:?>
  <div class="field<?= /* @escapeNotVerified */ $class ?>">
    <div class="spec">
      <label class="label" for="select_<?= /* @escapeNotVerified */ $option->getId() ?>">
          <span><?= $block->escapeHtml($option->getTitle()) ?></span>
      </label>
      <div class="control">
          <?= $block->getValuesHtml() ?>
          <?php if ($option->getIsRequire()): ?>
              <?php if ($option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_RADIO || $option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_CHECKBOX): ?>
                  <span id="options-<?= /* @escapeNotVerified */ $option->getId() ?>-container"></span>
              <?php endif; ?>
          <?php endif;?>
      </div>
    </div>
  </div>
  <?php endif;?>
  <script type="text/javascript">
      require(['jquery'], function ($) {
          'use strict';

          $(function () {
            // the selector will match all input controls of type :checkbox
            // and attach a click event handler
            $("input:checkbox").on('click', function() {
              // in the handler, 'this' refers to the box clicked on
              var $box = $(this);
              if ($box.is(":checked")) {
                // the name of the box is retrieved using the .attr() method
                // as it is assumed and expected to be immutable
                var group = "input:checkbox[name='" + $box.attr("name") + "']";
                // the checked state of the group/box on the other hand will change
                // and the current value is retrieved using .prop() method
                $(group).prop("checked", false);
                $box.prop("checked", true);
              } else {
                $box.prop("checked", false);
              }
            });
          });
      });
  </script>
