
  <?php
   $Id = $block->getData('id_path');
   $categoryId=filter_var($Id, FILTER_SANITIZE_NUMBER_INT);


    $_objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
    $categoryFactory = $_objectManager->get('\Magento\Catalog\Model\CategoryFactory');
    $categoryHelper = $_objectManager->get('\Magento\Catalog\Helper\Category');
    $categoryRepository = $_objectManager->get('\Magento\Catalog\Model\CategoryRepository');
    $imageHelper  = $_objectManager->get('\Magento\Catalog\Helper\Image');
    $productHelper = $_objectManager->create('Magento\Catalog\Model\Product');
    $productData = $_objectManager->create('Magento\Catalog\Model\ProductRepository');





    $category = $categoryFactory->create()->load($categoryId);




    $categoryProducts = $category->getProductCollection()
                                 ->addAttributeToSelect('*');
   if($block->getData('widgettitle')): ?>
   <div class="slider-title">
     <h2 class='widget-title'><?php echo $block->getData('widgettitle'); ?></h2>
   </div>
   <?php endif; ?>
   <div class="owl-carousel product-slider-home" id="todaysdeals">
     <?php
      foreach ($categoryProducts as $product) {
        ?>
      <div class="item">
        <a href="<?= /* @escapeNotVerified */ $product->getProductUrl() ?>">
          <?php
  $_price= $product->getPrice();

              $_finalPrice= $product->getSpecialPrice();
              $specialPriceFromDate = $product->getSpecialFromDate();
              $specialPriceToDate = $product->getSpecialToDate();
              $today =  time();
              if ($_finalPrice && ($product->getPrice()>$product->getFinalPrice())):
                if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) ||
                $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)):
                //product in sales
                $_savePercent = 100-round(($_finalPrice / $_price) * 100);
                ?>
                  <span class="discount-flag"><?php echo $_savePercent . "% Off";?></span>
                  <?php
                endif;
                endif;

          ?>

          <?php $image_url = $imageHelper->init($product, 'product_page_image_large')->setImageFile($product->getFile())->getUrl();?>
          <img src="<?php echo $image_url;?>" alt="product"/>
          <h3><?php echo $product->getName();?></h3>
          <p class="price"><span class="original-price <?php echo $product->getSpecialPrice() ? 'has-special-price' : '' ?>"><?php echo $product->getPrice();?></span><span class="discount-price"><?php echo $product->getSpecialPrice();?></span></p>
          <p class="subtext"><?php echo "or as low as";?><span class="amount"><?php echo" $10/month";?></span></p>
        </a>
      </div>
  <?php
      }
      ?>
  </div>
