<?php
/* @var $block \Mirasvit\Rma\Block\Rma\View\Message */
?>
<div class="block">
    <div class="block-content">
        <form action="<?= $block->getMessagePostUrl() ?>" method="POST" enctype="multipart/form-data"
              data-hasrequired="<?= __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
            <input name="id" type="hidden" value="<?= $block->getRmaId() ?>">

            <fieldset class="fieldset">
                <div class="field">
                    <label class="label">
                        <span><?= __('Add Message') ?></span>
                    </label>

                    <div class="control">
                        <textarea name="message" id="message" class="input-text"></textarea>
                    </div>
                </div>

                <div class="field">
                    <label class="label">
                        <span><?= __('Attach files') ?></span>
                    </label>

                    <div class="control">
                        <div class="curacao-file-upload">
                            <div class="file-upload">
                                <div class="file-select">
                                    <div class="file-select-button" id="fileName">Choose File</div>
                                    <div class="file-select-name" id="noFile">No file chosen</div>
                                    <?= $block->getFileInputHtml() ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?= $block->getAttachmentLimits() ?>
                </div>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action primary">
                        <span><?= __('Submit') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery'
    ], function($) {$(function() {

        $('#attachment').bind('change', function () {
            var filename = $("#attachment").val();
            if (/^\s*$/.test(filename)) {
                $(".file-upload").removeClass('active');
                $("#noFile").text("No file chosen...");
            }
            else {
                $(".file-upload").addClass('active');
                $("#noFile").text(filename.replace("C:\\fakepath\\", ""));
            }
        });

    });
    })
</script>
