<?php
/**
 * Dyode_curacao theme.
 *
 * Extending Magento_Catalog
 *
 * @package Dyode
 * @module  Dyode_curacao
 * @author  Rajeev K Tomy <rajeev.ktomy@dyode.com>
 * @copyright Copyright © Dyode
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 * @var $viewModel \Dyode\Catalog\ViewModel\Frontend\Catalog\Product\View\Addtocart
 */
$_product = $block->getProduct();
$buttonTitle = __('Add to Cart');
$viewModel = $block->getViewModel();
$qtySelectLimit = 10;
if ($viewModel) {
    $qtySelectLimit = $viewModel->getQtyLimit();
}
?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">

        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <div class="control">
                <select
                        name="qty"
                        id="qty"
                        title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                        class="input-text qty"
                        data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>">

                  <?php for($qtyIncr = 1; $qtyIncr <= $qtySelectLimit; $qtyIncr++): ?>
                      <option value="<?= $qtyIncr ?>" <?= ($qtyIncr === 1) ? 'selected': '' ?>><?= $qtyIncr ?></option>
                  <?php endfor; ?>

                </select>
            </div>
        </div>
        <?php endif; ?>

        <!-- TV wall mount option for tv -->
        <div class="product-spec-details tv-wallmount">
          <div class="wall-mount spec">
            <label class="label"><span><?= /* @escapeNotVerified */ __('TV wall mounting options') ?></span></label>
            <div class="control">
              <div class="input-radio"><input type="radio" id="without-installation" name="installation" value="without-installation" checked> <label for="without-installation">Without expert installation</label></div>
              <div class="input-radio"><input type="radio" id="with-installation" name="installation" value="with-installation"> <label for="with-installation">Expert wall mounting: $80</label></div>
            </div>
          </div>
        </div>
        <!-- TV wall mount option for tv -->

        <div class="add-to-cart-block">
          <div class="actions">
            <button type="button"
                title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                class="custom-button"
                id="product-addtocart-button">
                <span>
                  <img src="<?php echo $this->getViewFileUrl('images/cart-button.png'); ?>" />
                  <?= /* @escapeNotVerified */ $buttonTitle ?>
                </span>
            </button>
            <?=  $block->getChildHtml('', true) ?>
        </div>

        <!-- Static block for pick up product  -->
        <div class="shipping-pickup-details">
          <p class="shipping"><strong>Free Shipping: </strong>Get it by Wed, Jul 11</p>
          <p class="pickup-option">Want it today? <a href="#" id="pickup-location">Pict it up at Compton</a></p>
        </div>
        <!-- End Static block for pick up product  -->
      </div>

      <!-- Check store new static block -->
      <div class="check-store">
        <a href="">Check Store</a>
      </div>
      <!-- End Check store new static block -->
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
