<div class="frequently-bought-items">
  <h3>Frequently bought together</h3>
  <div class="frequently-product-block" id="frequent-items">
    <div class="product slected-item">
      <div class="prod-details">
        <img class="prod-img" src="<?php echo $this->getViewFileUrl('images/iphone.png'); ?>" />
        <div class="price-details">
          <label class="name">iPhone 8</label>
          <p class="price">
            <label>$799.99</label>
            <label class="off-price">30% Off</label>
          </p>
        </div>
      </div>
    </div>
    <label class="include-item"><img class="prod-add" src="<?php echo $this->getViewFileUrl('images/add.png'); ?>" /></label>
    <div class="product frequent-item">


      <div class="prod-details">
        <img class="prod-img" src="<?php echo $this->getViewFileUrl('images/Tempered-Glass.png'); ?>" />
        <div class="price-details">
          <label class="name">Amzer Tempered glass</label>
          <p class="price">
            <label>$101.99</label>
            <label class="off-price">30% Off</label>
          </p>
        </div>
      </div>
    </div>
    <label class="include-item"><img class="prod-add" src="<?php echo $this->getViewFileUrl('images/add.png'); ?>" /></label>
    <div class="product frequent-item">

      <div class="prod-details">
        <img class="prod-img" src="<?php echo $this->getViewFileUrl('images/airpods.png'); ?>" />
        <div class="price-details">
          <label class="name">Apple Air pods</label>
          <p class="price">
            <label>$100.99</label>
            <label class="off-price">30% Off</label>
          </p>
        </div>
      </div>
    </div>
  </div>

</div>
