<?php
/**
 * Dyode_curacao theme.
 *
 * Extending Magento_Catalog
 *
 * @package   Dyode
 * @module    Dyode_curacao
 * @author    Kavitha <kavitha@dyode.com>
 * @copyright Copyright © Dyode
 */
?>
<?php
/**
 * @var $block     \Magento\Catalog\Block\Product\View
 * @var $viewModel \Dyode\Catalog\ViewModel\Frontend\Catalog\Product\View\Soldout
 * @var $soldoutProduct \Magento\Catalog\Model\Product
 */
$viewModel = $block->getViewModel();
$product = $block->getProduct();
?>


<?php if ($viewModel->canShowSoldout($product)): ?>
    <div class="outer-messsage">
        <div class="out-of-stock">
            <img src="<?php echo $block->getViewFileUrl('images/out-of-stock-box.png'); ?>" alt="Out Of Stock" />
            <span class="first-part">
                <span class="outofstock"> <?php echo __("Sold Out Online");?> </span>
                <?php echo __("!");?>
            </span>
        </div>
    </div>
<?php endif; ?>
