<?php
/**
 * Dyode_curacao theme.
 *
 * Extending Magento_Catalog
 *
 * @package   Dyode
 * @module    Dyode_curacao
 * @author    Kavitha <kavitha@dyode.com>
 * @copyright Copyright © Dyode
 */
?>
<?php
/**
 * @var $block     \Magento\Catalog\Block\Product\View
 * @var $viewModel \Dyode\Catalog\ViewModel\Frontend\Catalog\Product\View\Soldout
 * @var $soldoutProduct \Magento\Catalog\Model\Product
 */
$viewModel = $block->getViewModel();
$product = $block->getProduct();
?>

<?php if ($viewModel->canShowFbt($product)): ?>

    <?php
    $fbtProducts = $viewModel->fbtProducts($product);
    $discount = $viewModel->productDiscount($product);
    //to remove double slashes in product image URL
    $routeName =$viewModel->getProductImageUrl($product);
    $routeNamePart1 = substr( $routeName, 0 , strpos($routeName,'//') +4 );
    $routeNamePart2 = substr( $routeName, strpos($routeName,'//') + 4);
    $routeNamePart2 = str_replace('//', '/' , $routeNamePart2);
    $imageURL = $routeNamePart1 . $routeNamePart2;
    ?>
<?php endif;?>