<?php
/**
 * Dyode_curacao theme.
 *
 * Extending Magento_Catalog
 *
 * @package   Dyode
 * @module    Dyode_curacao
 * @author    Rajeev K Tomy <rajeev.ktomy@dyode.com>
 * @copyright Copyright © Dyode
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block     \Magento\Framework\View\Element\Template
 * @var $viewModel \Dyode\Catalog\ViewModel\Frontend\Catalog\Product\View\StoreAvailability
 */
$viewModel = $block->getViewModel();
$shippingDaysLabel = $viewModel->shippingDaysLabel();
?>

<?php if ($viewModel->canShowNearestStore()): ?>
    <?php $nearestStore = $viewModel->nearestStore(); ?>
    <div class="shipping-pickup-details">
        <p class="shipping">
            <strong><?= __("FREE Shipping") ?>: </strong><?= __($shippingDaysLabel); ?>
        </p>

        <p class="pickup-option"><?= __("Want it today?") ?>
            <span id="pickup-location"><?= __("Pick it up at") ?> <?= __($nearestStore->getName()) ?></span>
        </p>
    </div>
<?php endif; ?>

<div id="store-availability">
    <div id="store-availability-check" class="check-store">
        <a href="#"><?= __("Check Store Availability") ?></a>
    </div>

    <div id="store-availability-form" class="store-availability-form" style="display: none">
        <div class="title"><?= __('Check Store Availability') ?></div>
        <div class="messages"></div>
        <div class="form-field-container">
            <div class="form-field">
                <input type="number"
                       class="zip-field required zipUS"
                       placeholder="<?= __('Please enter your zipcode') ?>"
                       id="store-availability-zip-field"
                />
            </div>
            <div class="form-field">
                <button class="submit" type="button"><span><?= __('Check') ?></span></button>
            </div>
            <div class="form-field">
                <a id="store-avail-form-cancel" class="close"><span><?= __('Cancel') ?></span></a>
            </div>
        </div>
    </div>

    <div id="store-availability-modal" style="display:none;">
        <div id="dialog-message" class="message"><!-- Here Modal data will be populated --></div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#store-availability": {
            "Magento_Catalog/js/store-availability": <?= $viewModel->storeAvailabilityJsData() ?>
        }
    }
</script>
