<?php
/**
 * Dyode_curacao theme.
 *
 * Extending Magento_Catalog
 *
 * @package Dyode
 * @module  Dyode_curacao
 * @author  Rajeev K Tomy <rajeev.ktomy@dyode.com>
 * @copyright Copyright © Dyode
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $productViewBlock \Magento\Catalog\Block\Product\View
 * @var $viewModel \Dyode\Catalog\ViewModel\Frontend\Catalog\Product\View\Warranty
 */
$viewModel = $block->getViewModel();
$productViewBlock = $block->getParentBlock();
$warranties = $viewModel->setProduct($productViewBlock->getProduct())->warrantyProducts();
?>
<?php if(count($warranties) > 0): ?>
<div class="warranty-plan" id="warranty_options">
    <h3 class="warranty-title"><?= __("Add a warranty plan") ?></h3>
    <div class="warranty-select">
        <div id="warranty-check" class="js-warranty-select">

            <?php foreach($warranties as $warranty): ?>
                <?php /** @var $warranty \Magento\Catalog\Model\Product */ ?>
                <label class="warranty-box">
                    <?= __("Include ") ?>
                    <a href="#"
                       class="warranty-link"
                       id="warranty-link<?= $warranty->getId() ?>"
                       data-cms-block-id="21"
                       data-warranty-id="<?= $warranty->getId() ?>"
                    >
                        <?= $warranty->getName() ?>
                    </a> <?= __("for ") ?><?= $viewModel->formattedPrice($warranty) ?>
                    <input type="checkbox"
                           name="warranty[<?= $warranty->getId() ?>]"
                           id="warranty-option-<?= $warranty->getId() ?>"
                    />
                    <span class="checkmark"></span>
                </label>
            <?php endforeach; ?>
        </div>

    </div>
</div>
<div id="warrantyModal" class="modal">
    <div class="modal-content">
        <input type="hidden" name="warranty" value="" />
        <div class="product-details">
            <div class="top-section"></div>

            <div class="waranty-details">
                <p class="price"><?= __("Price") ?>: <span class="warranty-price"></span></p>
                <div class="warranty-description"></div>
                <a href="#" class="learn-more-link">Learn More</a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#warranty_options": {
            "Magento_Catalog/js/warranty-options": <?= $viewModel->getWarrantyJsData() ?>
        }
    }
</script>
