<?php
/**
 * Dyode_curacao theme.
 *
 * Extending Magento_Catalog
 *
 * @package Dyode
 * @module  Dyode_curacao
 * @author  Rajeev K Tomy <rajeev.ktomy@dyode.com>
 * @copyright Copyright © Dyode
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $productViewBlock \Magento\Catalog\Block\Product\View
 * @var $viewModel \Dyode\Catalog\ViewModel\Frontend\Catalog\Product\View\Warranty
 */
$viewModel = $block->getViewModel();
$productViewBlock = $block->getParentBlock();
$warranties = $viewModel->setProduct($productViewBlock->getProduct())->warrantyProducts();
$isModal = (bool)$block->getData('is_modal');
?>
<?php if(count($warranties) > 0): ?>
<div class="warranty-plan" id="warranty_options<?= $isModal ? '_modal': '' ?>">
    <h3 class="warranty-title"><?= __("Add a Protection Plan") ?></h3>
    <div class="warranty-select">
        <div id="warranty-check" class="js-warranty-select">

            <?php foreach($warranties as $warranty): ?>
                <?php /** @var $warranty \Magento\Catalog\Model\Product */ ?>
                <label class="warranty-box">
                    <?= __("Include ") ?>
                    <a href="#"
                       class="warranty-link"
                       id="warranty-link<?= $isModal ? '-modal': '' ?>-<?= $warranty->getId() ?>"
                       data-warranty-id="<?= $warranty->getId() ?>"
                    >
                        <?= $warranty->getName() ?>
                    </a> <?= __("for ") ?><?= $viewModel->formattedPrice($warranty) ?>
                    <input type="checkbox"
                           name="warranty[<?= $warranty->getId() ?>]"
                           id="warranty-option<?= $isModal ? '-modal': '' ?>-<?= $warranty->getId() ?>"
                           value="<?= $warranty->getId() ?>"
                    />
                    <span class="checkmark"></span>
                </label>
            <?php endforeach; ?>
        </div>

    </div>
</div>

<?= $block->getChildHtml(''); ?>

<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#warranty_options": {
            "Magento_Catalog/js/warranty-options": <?= $viewModel->getWarrantyJsData() ?>
        }
    }
</script>
