<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Login to Curacao')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" placeholder="Enter your Email ID" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" placeholder="Password" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="secondary">
                      <a class="action remind forget-password" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a>
                      <p class="sign-up">New in Curacao? &nbsp;<a href="<?= $block->escapeUrl($block->getUrl('customer/account/create')); ?>" class="action create primary"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a></p>
                    </div>
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Login')) ?></span></button></div>

                </div>
            </fieldset>
        </form>
    </div>
    <!-- Card logo and card images -->
    <div class="curacao-card">
      <div class="card-images">
        <img src="<?php echo $this->getViewFileUrl('images/curacaoCreditLogo.png'); ?>" class="credit-card-logo" alt="credit-card" />
        <img src="<?php echo $this->getViewFileUrl('images/curaco_card.png'); ?>" class="credit-card" alt="credit-card" />
      </div>
    </div>
</div>
<!-- Card apply block -->
<div class="curacao-card-apply">
  <div class="content">
    <p>Get instant  Curacao Credit approval</p>
  </div>
  <div class="apply-now-button">
    <a href="" class="apply-now">Apply Now</a>
  </div>
</div>
