<!-- Event snippet for Sales_Conversion conversion page -->
<?php
$order = Mage::getModel('sales/order')->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId());
$orderID = $order->getIncrementId();
$grandTotal = $order->getGrandTotal();
exit();
?>
<script>
    gtag('event', 'conversion', {
        'send_to': 'AW-984938519/X7RvCMa3s2UQl_DT1QM',
        'value': '<?php echo $grandTotal;?>',
        'currency': 'USD',
        'transaction_id': '<?php echo $orderID; ?>'
    });
</script>

