<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Dyode\OrderDetails\Block\Onepage\Success */ ?>
<?php $order = $block->getOrder($block->getOrderId()); ?>
<?php $helper = $this->helper('Dyode\OrderDetails\Helper\Data'); ?>
<?= $block->getAdditionalInfoHtml() ?>
<div class="order-confirmation-container">
  <div class="order-confirmation-content">
    <div class="top-section">
      <!-- Order Confirmation Section with success message and order number  -->
       <div class="curacaoOrder-status">
          <img src="<?php echo $block->getViewFileUrl('images/dart-board.png'); ?>" alt="Success Icon">
          <h1 class="success-message"><?php echo __('Order Successfully Placed')?></h1>
       </div>
       <div class="status-details">
         <h3><?php echo __('Thank you for your purchase! Your order has been received.')?>'</h3>
            <?php if ($block->getOrderId()): ?>
              <?php if ($block->getCanViewOrder()) : ?>
                <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
              <?php else : ?>
                <p><?= __('Your order is: #<span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
              <?php endif; ?>
               <p><?= /* @escapeNotVerified */ __('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
           <?php endif; ?>
       </div>
        <!--       //shiipping info , billing info , payment , order details , delivery date block  -->
        <div class="section-wrapper">
          <div class="purchase-details">
            <!--shipping address  -->
            <div class="block">
              <div class="block-title">
                <h2><?php /* @escapeNotVerified */ echo __('Shipping address'); ?></h2>
               </div>
               <address>
                 <?php echo $block->getFormatedAddress($order->getShippingAddress()); ?>
               </address>
             </div>
             <!--billing address  -->
             <div class="block">
                <div class="block-title">
                    <h2><?php /* @escapeNotVerified */ echo __('Billing Address'); ?></h2>
                 </div>
                <address>
                    <?php echo $block->getFormatedAddress($order->getBillingAddress()); ?>
                </address>
             </div>
             <!--payment  -->
             <div class="block payment-method-outer">
                <div class="each-details">
                  <div class="block-title">
                    <h2><?php /* @escapeNotVerified */ echo __('Payment Method'); ?></h2>
                  </div>
                  <div class="details">
                    <?php echo $block->getPaymentMethodtitle($order); ?>
                 </div>
              </div>
          </div>
       </div>
       <!--Cart product details   -->
       <div class="order-details">
         <div class="block ord-det">
           <div class="block-title">
             <h2><?php echo __('Order Details')?></h2>
           </div>
           <div class="product-details">
             <?php foreach ($order->getAllVisibleItems() as $item) :?>
               <div class="each-product-outer">
                  <div class="each-product">
                    <?php
                        $product = $helper->getProductById($item->getProductId());
                        $options = $item->getProductOptions();
                        $imageBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
                        $productImage = $imageBlock->getImage($product, 'category_page_list'); ?>
                      <div class="product-image">
                          <a href="<?php echo $product->getProductUrl(); ?>"><?php echo $productImage->toHtml(); ?></a>
                      </div>
                      <div class="product-info">
                                  <div class="pdt-name">
                                    <h3>
                                      <?php echo $item->getName(); ?>
                                    </h3>
                                  </div>
                                  <div class="pdt-price">
                                   <?php echo $helper->getFormatedPrice($item->getPrice()); ?>
                                 </div>
                                <div class="qty">
                                  <?php echo __('Quantity:')?>
                                 <span>
                                   <?php echo  intval($item->getQtyOrdered()); ?>
                                 </span>
                               </div>
                       </div>
                  </div>
                  <!-- Right side -->
                  <div class="block delivery-date-outer">
                    <div class="block-title">
                      <h2><?php echo __('Delivery')?></h2>
                    </div>
                    <?php
                        $pickupLocation = $item->getPickupLocation();
                        $address =  $block->getPickupLocation($pickupLocation);  
                    ?>
                    <?php 
                        if($pickupLocation) { 
                           $addressDetails = $address->getData();
                    ?>
                      <div class="store-location-details">
                        <label><?php echo __('Store Pickup')?></label>
                        <div class="store-location-content">
                          <div class="title"><?php echo $addressDetails['title']; ?></div>
                          <div class="address"><?php echo $addressDetails['city']; ?></div>
                          <div class="cityAbbrZip"><?php echo $addressDetails['street'] . "  ". $addressDetails['zip']; ?></div>
                        </div>
                      </div>
                    <?php } else { ?>
                    <?php 
                         $shippingDetails =  json_decode($item->getShippingDetails());
                         $carrierCode = $shippingDetails->carrier_code;
                         $carrierMsg =  $block->collectShippingMethodDeliveryMsgs();
                         switch($carrierCode){
                            case 'ups':
                                        $methodCode = $shippingDetails->method_code;
                                        switch($methodCode){
                                            case 'GND': 
                                                      $message = $carrierMsg['ups'];
                                                      break;
                                            case '2DA':
                                                      $message = date('M d,Y', strtotime("+2 days"));
                                                      break;
                                            case '3DS':
                                                      $message = date('M d,Y', strtotime("+3 days"));
                                                      break;
                                        }
                                        break;
                            case 'usps': $message = $carrierMsg['usps'];
                                         break;
                            case 'adsmomentum': $message = $carrierMsg['adsmomentum'];
                                            break;
                            case 'pilot': $message = $carrierMsg['pilot'];
                                            break;                

                         }
                        
                    ?>  
                      <div class="delivery-date-details">
                      <label><?php echo __('Estimated delivery'); ?></label>
                      <div class="delivery-date">
                      <?php echo $message; ?>
                      </div>
                    </div>
                    <?php } ?>
                  </div>
                </div>  
                <?php endforeach; ?>
           </div>
         </div>

       </div>

      </div>
</div>
  <div class="actions-toolbar">
    <div class="primary">
    <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>">
        <span><?php echo /* @escapeNotVerified */ __('Continue Shopping'); ?></span>
    </a>
  </div>
</div>
</div>
</div>
