<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<div class="order-confirmation-container">
  <div class="order-confirmation-content">
    <div class="top-section">
      <!-- Order Confirmation Section with success message and order number  -->
      <div class="curacaoOrder-status">
        <img src="<?php echo $block->getViewFileUrl('images/dart-board.png'); ?>" alt="Success Icon">
        <h1 class="success-message">Order Successfully Placed</h1>
      </div>
      <div class="status-details">
        <h3>Thank you for your purchase! Your order has been received.</h3>

        <?php if ($block->getOrderId()):?>
            <?php if ($block->getCanViewOrder()) :?>
                <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
            <?php  else :?>
                <p><?= __('Your order is: <span class="order-no">#%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
            <?php endif;?>

        <?php endif;?>

        <?= $block->getAdditionalInfoHtml() ?>

        <p>You will receive an order confirmation email with details of your order and a link to track its progress.</p>
      </div>
      <!--       //shiipping info , billing info , payment , order details , delivery date block  -->
      <div class="section-wrapper">
        <div class="purchase-details">
          <div class="block">
            <div class="block-title">
              <h2>Shipping address</h2>
            </div>
            <address>
              John Doe
              <br/> 2560 MALLORY CIR
              <br/> ST 101 Franklin Street
              <br/> KISSIMMEE, FL 34747-1818
              <br/> United States
              <br/> Phone: +12816782564
              <br/>
            </address>
          </div>
          <div class="block">
            <div class="block-title">
              <h2>Billing address</h2>
            </div>
            <address>
              John Doe
              <br/> 2560 MALLORY CIR
              <br/> ST 101 Franklin Street
              <br/> KISSIMMEE, FL 34747-1818
              <br/> United States
              <br/> Phone: +12816782564
              <br/> </address>
          </div>
          <div class="block">
            <div class="each-details">
              <div class="block-title">
                <h2>Payment info.</h2>
              </div>
              <div class="details">
                  <img src="<?php echo $block->getViewFileUrl('images/curacao-card.jpg'); ?>" alt="credit card icon">
                <span> ending in XXXX 3135</span>
              </div>
            </div>
            <div class="each-details">
              <div class="block-title">
                <h2>Initial payment</h2>
              </div>
              <div class="details">
                    <img src="<?php echo $block->getViewFileUrl('images/visa-card.jpg'); ?>" alt="credit card icon">

                <span> ending in XXXX 3135</span>
              </div>
            </div>
          </div>
        </div>
        <!--Cart product details   -->
        <div class="order-details">
          <div class="block ord-det">
            <div class="block-title">
              <h2>Order Details</h2>
            </div>
            <div class="product-details">
              <div class="each-product">
                <div class="product-image">
                    <img src="<?php echo $block->getViewFileUrl('images/product-image.jpg'); ?>" alt="product image">

                </div>
                <div class="product-info">
                  <div class="pdt-name">
                    <h3>Apple iPhone 8 4.7", 64 GB, Gold</h3>
                  </div>
                  <div class="pdt-price">
                    <span>$822.99</span>
                  </div>
                  <div class="qty">
                    Quantity:
                    <span>1</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Estimated Delivery Date -->
          <div class="block delivery">
            <div class="block-title">
              <h2>Delivery</h2>
            </div>
            <div class="est-date">
              Estimated delivery:
              <div class="date">July 13, 2018</div>
            </div>
          </div>
        </div>

      </div>
    </div>
 <!--Continue Shopping action button  -->
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>

  </div>
</div>
<!-- Price Beat and Interest Beat Block -->
<div class="guarantee-block">
  <div class="left-block">
    <div class="image">
          <img src="<?php echo $block->getViewFileUrl('images/price-beat.png'); ?>" alt="Price Beat Logo">
    </div>
    <div class="details">
      <h2>Price Beat</h1>
        <h3>Gurantee</h3>
        <p>We'll beat any competitor's price</p>
    </div>
  </div>
  <div class="right-block">
    <div class="image">
      <img src="<?php echo $block->getViewFileUrl('images/interest-beat.png'); ?>" alt="Interest Beat Logo">
    </div>
    <div class="details">
      <h2>Interest Beat</h1>
        <h3>Gurantee</h3>
        <p>We'll beat any competitor's price</p>
    </div>
  </div>
</div>
