<?php
/**
 * Copyright 2018 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

/* @var $block \Aheadworks\StoreLocator\Block\Adminhtml\Page\Menu */

// @codingStandardsIgnoreFile

?>
<div class="<?= $block->escapeHtml($block->getClassName()) ?>">
    <div class="actions dropdown closable">
        <button type="button" class="admin__action-dropdown" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
            <span class="admin__action-dropdown-text"><?= $block->escapeHtml($block->getCurrentItemTitle()) ?></span>
        </button>
        <ul class="dropdown-menu">
            <?php foreach ($block->getMenuItems() as $index => $item): ?>
                <li class="<?php if ($block->isCurrent($index)): ?>current<?php endif; ?> <?php if (isset($item['separator'])): ?>separator<?php endif; ?>">
                    <a href="<?= $block->escapeUrl($item['url']) ?>" <?= $block->escapeHtmlAttr($block->renderAttributes($item)) ?>><?= $block->escapeHtmlAttr($item['title']) ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
