<div class="footer-bottom-block">
  <?php
    echo $this->getLayout()
               ->createBlock('Magento\Cms\Block\Block')
               ->setBlockId('bottom_footer_content')
               ->toHtml();
   ?>
   <?php
     echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('bottom_footer_content_esp')
                ->toHtml();
    ?>
</div>
