<div class="side-banner">
  <a href="">
    <!-- <img class="desk-banner" src="images/cur-cre-banner.jpg" alt="banner">
    <img class="resp-banner" src="images/cur-cre-banner-resp.jpg" alt="banner"> -->
    <img class="desk-banner" src="<?php echo $block->getViewFileUrl('images/cur-cre-banner.jpg'); ?>" alt="side-banner" />
    <img class="resp-banner" src="<?php echo $block->getViewFileUrl('images/cur-cre-banner-resp.jpg'); ?>" alt="side-banner" />
  </a>
</div>
