<nav class="sidebar" id="sidebar">
  <div class="sidebar-container"><h2>Hello, Sign in<span class="sidebar__btn-close" id="sidebarBtnClose"><span></h2></div>
  <ul>
    <li><a href="#"><?php echo __('Curacao Credit'); ?></a></li>
    <li><a href="#"><?php echo __('Pay Bill'); ?></a></li>
    <li><a href="#"><?php echo __('Digital Catalog'); ?></a></li>
    <li class="hamburger-link-border"><a href="/store-locator"><?php echo __('Our Stores'); ?></a></li>
    <li><a href="#"><?php echo __("Today's Deal"); ?></a></li>
    <li class="hamburger-link-border"><a href="/clearance-sale"><?php echo __('Sale'); ?></a></li>
    <li class="hamburger-heading"><a href="#"><?php echo __('Help & Settings'); ?></a></li>
    <li><a href="/customer/account/login/"><?php echo __('Your Account'); ?></a></li>
    <!-- Store Switcher Start -->
    <?php if ($block->getStoreCode() == 'default') : ?>
      <li class="hamburger-language"><a href="?___store=es"><img src="<?php echo $block->getViewFileUrl('images/lang-icon.png'); ?>" alt="lang-icon" />ESPANOL</a></li>
    <?php else: ?>
      <li class="hamburger-language"><a href="?___store=default"><img src="<?php echo $block->getViewFileUrl('images/lang-icon.png'); ?>" alt="lang-icon" />ENGLISH</a></li>
    <?php endif; ?>
    <!-- Store Switcher End -->
    <li><a href="#"><?php echo __('Customer Service'); ?></a></li>
  </ul>
</nav>
<div class="sidebar-overlay"></div>
