<div class="store-view-container">
  <ul>
    <!-- Store Switcher Start -->
    <?php if ($block->getStoreCode() == 'default') : ?>
      <li class="hamburger-language"><a href="?___store=es"><img src="<?php echo $block->getViewFileUrl('images/lang-icon.png'); ?>" alt="lang-icon" />ESPANOL</a></li>
    <?php else: ?>
      <li class="hamburger-language"><a href="?___store=default"><img src="<?php echo $block->getViewFileUrl('images/lang-icon.png'); ?>" alt="lang-icon" />ENGLISH</a></li>
    <?php endif; ?>
    <!-- Store Switcher End -->
    <li class="stores"><a href="/store-locator">Our Stores</a></li>
  </ul>
</div>
