<?php
/**
 * Copyright 2018 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */
 $tab = $this->getTab() ? $this->getTab() : 0; ?>

<div class="aw-storelocator-search-block" id="aw-storelocator-search-block">
    <div class="product info detailed">
        <div class="product data items"
             data-mage-init='{"tabs":{"openedState":"active", "active": <?= $block->escapeHtml($tab) ?>}}'>
            <div class="data item title"
                 aria-labeledby="tab-label-aw-distance-title"
                 data-role="collapsible" id="tab-label-aw-distance">
                <a class="data switch"
                   tabindex="-1"
                   data-toggle="switch"
                   href="#aw-distance"
                   id="tab-label-aw-distance-title">
                    <?= $block->escapeHtml(__('Search by Distance')); ?>
                </a>
            </div>
            <div class="data item content" id="aw-distance" data-role="content">
                <form method="post" action="" id="aw-search-form" data-mage-init='{"validation": {}}'>
                    <fieldset class="fieldset">
                        <div class="field address">
                            <label for="address" class="label"><?= $block->escapeHtml(__('Current Location')) ?></label>
                            <div class=control">
                                <input type="text"
                                       name="search[street]"
                                       id="street"
                                       value="<?= $this->escapeHtml($this->getStreet()); ?>"
                                       title="<?= $block->escapeHtml(__('Current Location')) ?>"
                                       class="input-text" />
                                <?php if ($this->isFindMyLocationButtonEnabled()) : ?>
                                <button type="button"
                                        class="action submit primary"
                                        id="aw-find-location"
                                        title="<?= $block->escapeHtml(__('Find My Location')) ?>">
                                    <span><?= $block->escapeHtml(__('Find My Location')) ?></span>
                                </button>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="field radius">
                            <label for="radius" class="label">
                                <?= $block->escapeHtml(__('Search Radius')) ?>
                            </label>
                            <?= $this->getSearchRadiusElementHtml(); ?>
                        </div>
                        <div class="field measurement">
                            <label for="measurement" class="label">
                                <?= $block->escapeHtml(__('Search Radius Measurement')) ?>
                            </label>
                            <?= $this->getSearchMeasurementElementHtml(); ?>
                        </div>
                    </fieldset>
                    <input type="hidden"
                           id="latitude"
                           name="search[latitude]"
                           value="<?= $block->escapeHtml($this->getLatitude()); ?>" />
                    <input type="hidden"
                           id="longitude"
                           name="search[longitude]"
                           value="<?= $block->escapeHtml($this->getLongitude()); ?>" />
                    <input type="hidden" id="tab1" name="search[tab]" value="0" />
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit"
                                    class="action submit primary"
                                    title="<?= $block->escapeHtml(__('Search')) ?>">
                                <span><?= $block->escapeHtml(__('Search')) ?></span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="data item title"
                 aria-labeledby="tab-label-aw-address-title"
                 data-role="collapsible" id="tab-label-aw-address">
                <a class="data switch"
                   tabindex="1"
                   data-toggle="switch"
                   href="#aw-address"
                   id="tab-label-aw-address-title">
                    <?= $block->escapeHtml(__('Search by Address')); ?>
                </a>
            </div>
            <div class="data item content" id="aw-address" data-role="content">
                <form method="post" action="" id="aw-search-form" data-mage-init='{"validation": {}}'>
                    <fieldset class="fieldset">
                        <div class="field country">
                            <label for="country" class="label"><?= $block->escapeHtml(__('Country')) ?></label>
                            <?= $this->getCountryElementHtml(); ?>
                        </div>
                        <div class="field region">
                            <label for="region" class="label"><?= $block->escapeHtml(__('Region / State')) ?></label>
                            <?= $this->getRegionElementHtml(); ?>
                        </div>
                        <div class="field city">
                            <label for="city" class="label"><?= $block->escapeHtml(__('City')) ?></label>
                            <div class=control">
                                <input type="text"
                                       name="search[city]"
                                       id="city"
                                       value="<?= $this->escapeHtml($this->getCity()); ?>"
                                       title="<?= $block->escapeHtml(__('City')) ?>"
                                       class="input-text" />
                            </div>
                        </div>
                        <div class="field zip">
                            <label for="zip" class="label"><?= $block->escapeHtml(__('Zip')) ?></label>
                            <div class=control">
                                <input type="text"
                                       name="search[zip]"
                                       id="zip"
                                       value="<?= $this->escapeHtml($this->getZip()); ?>"
                                       title="<?= $block->escapeHtml(__('Zip')) ?>"
                                       class="input-text" />
                            </div>
                        </div>
                    </fieldset>
                    <input type="hidden"
                           id="region_id"
                           name="search[region_id_hidden]"
                           value="<?= $block->escapeHtml($this->getRegionId()); ?>"
                           disabled />
                    <input type="hidden" id="tab2" name="search[tab]" value="1" />
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit"
                                    class="action submit primary"
                                    title="<?= $block->escapeHtml(__('Search')) ?>">
                                <span><?= $block->escapeHtml(__('Search')) ?></span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
    "#aw-storelocator-search-block": {
        "Aheadworks_StoreLocator/js/search-location": {}
    }
}
</script>

<script>
    require([
        "jquery",
        "mage/adminhtml/form"
    ], function(){

        var updater = new RegionUpdater(
            'aw-storelocator-search-block-country',
            'region_id_hidden',
            'aw-storelocator-search-block-region',
            <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
            'disable'
        );
        updater.disableRegionValidation();

        window.updater = updater;
    });
</script>

