 <div class="linkaccount-container">
      <div class="linkaccount-inner-container">
        <div class="wrapper clearfix">
          <div class="verifymsg"></div>

<!--Verification code entry form-->
        <div class="verify-phone">
            <form class="verifyform" id="verifyform" method="post"
            autocomplete="off" action="<?php echo $block->getCodeFormAction(); ?>" data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset verify-wrapper">
                <legend class="legend"><span><?php echo __('Verify Account by Phone') ?>:</span></legend><br/>
                <p class="confirm-acct"><?php echo __('To confirm your account, we will send you a security code')?>.</p>
                <p><?php echo __('Please select one of the following options')?>.</p>
<!--Buttons to choose from sms verification or call verification-->
                <div class="contact-wrapper">
                  <button id="sendtext" name="sendtext" value="Text"> <?php echo __('SMS') ?> </button>
                  <div class="contact-icon1">
                    <img src="<?php echo $block->getViewFileUrl('images/sms-icon.png'); ?>" alt="sms icon" />
                  </div>
                  <button id="voice" name="voice" value="Voice"> <?php echo __('Call') ?> </button>
                  <div class="contact-icon2">
                    <img src="<?php echo $block->getViewFileUrl('images/call-icon.png'); ?>" alt="call icon" />
                  </div>
                </div>
<!--Input validation code-->
                <div class="field required">
                        <div class="control">
                            <input id="verification_code" type="text"
                            name="verification_code" value="" placeholder="Enter Verification Code"
                            class="input-text" data-validate="{required:true}" />
                        </div>
                </div>
            </fieldset>
<!--Submit form-->
            <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action submit primary"
                        title="<?php  echo __('Verify Account') ?>" id="verifycode"><span><?php echo __('Verify Account') ?></span>
                       </button>
                    </div>
                </div>
                <div class="disclaimer">
                  <p>If you don't recognize the number on file, please call 877-287-2226</p>
                </div>
            </form>
        </div>
<!--Divider between 2 forms-->
        <div class="or-spacer">
         <span><i>or</i></span>
        </div>
<!--Personal information form-->
        <div class="personal-infm">

          <form class="pinfm" id="pinfm" method="post" autocomplete="off"
          action="<?php echo $block->getFormAction(); ?>" data-mage-init='{"validation":{}}'>
<!--Enter fields required for verification - ssn no:,dob,zipcode and maiden name-->
          <fieldset class="fieldset">
              <legend class="legend"><span><?php echo __('Verify Personal Information') ?>:</span></legend><br/>
              <p><?php echo __('To confirm your account, please complete')?><br /><?php echo __('the following information.')?> </p>
                <span class="errormsg"> </span>
                <div class="verifymsg_docs" style="display:none;"><?php echo __("Please enter details for verification"); ?></div>

                 <div class="field ssn-field">
                        <label for="ssn-verify" class="label">
                        <span><?php echo __('Enter Last 4 Digits of your SSN ') ?></span></label>
                      <div class="control">
                          <span class="ssn-number"><?php echo __('XXX-XX-') ?></span>
                          <input id="ssn-verify" type="text" name="ssn-verify"
                          class="input-text ssn-field" maxlength="4"
                          data-validate="{'validate-number':true}"/>
                      </div>
                  </div>
                  <div class="field ">
                      <label for="link_email" class="label"><span><?php echo __('Date of Birth') ?></span></label>
                      <div class="control">
                      <input type="text" class="input-text"
                      id="calendar_inputField" name="calendar_inputField"
                      placeholder="Enter Date of Birth" />
                      </div>
                  </div>
                  <div class="field">
                      <label for="link_zipcode" class="label"><span><?php echo __('Zipcode') ?></span></label>
                      <div class="control">
                          <input id="link_zipcode" type="text" name="link_zipcode"
                          class="input-text" data-validate="{'validate-zip-us':true}"
                          placeholder="Enter Zipcode">
                      </div>
                  </div>
                  <div class="field">
                      <label for="link_maiden" class="label"><span><?php echo __("Mother's Maiden Name") ?></span></label>
                      <div class="control">
                          <input id="link_maiden" type="text" name="link_maiden" class="input-text"
                          data-validate="{'letters-only':true}" placeholder="Enter Mother's Maiden name">
                      </div>
                  </div>
                  <p><?php echo __('Please enter SSN and DOB OR Mothers Maiden Name and Zipcode OR Mothers Maiden Name and DOB'); ?></p>
          </fieldset>
<!--Submit form-->
          <div class="actions-toolbar">
                  <div class="primary">
                      <button type="button" class="action submit primary"
                       title="<?php  echo __('Submit') ?>" id="verifydocs"><span><?php echo __('Verify account') ?></span></button>
                 </div>
               </div>
             </form>
           </div>
          <div class="clear"></div>
        </div>
      </div>
    </div>
<!--Functionalities for form inputs-datepicker and restriction of entry to numbers or according to the rules-->
<script>
     require([
          "jquery",
          "mage/calendar"
     ], function($,calendar){
         $("#calendar_inputField").calendar({
              buttonText:"<?php echo __('Select Date') ?>",
              dateFormat: "mm-dd-yy",
              changeMonth: true,
              changeYear: true,
              yearRange: '1850:2020'
         });
         $("#ssn-verify").keypress(function(e){
             var keyCode = e.which;
             if ( (keyCode != 8 || keyCode ==32 ) && (keyCode < 48 || keyCode > 57)) {
               return false;
             }
          });
          $("#verification_code").keypress(function(e){
              var keyCode = e.which;
              if ( (keyCode != 8 || keyCode ==32 ) && (keyCode < 48 || keyCode > 57)) {
                return false;
              }
           });
           $("#link_zipcode").keypress(function(e){
               var keyCode = e.which;
               if ( (keyCode != 8 || keyCode ==32 ) && (keyCode < 48 || keyCode > 57)) {
                 return false;
               }
            });
           $("#link_maiden").keypress(function(e){
               var keyCode = e.which;
               if ( !( (keyCode >= 65 && keyCode <= 90)
                 || (keyCode >= 97 && keyCode <= 122) )
                 && keyCode != 8 && keyCode != 32) {
                 e.preventDefault();
               }
            });
            /**
            * Functions for the following conditions
            * Doc A Users - SSN and DOB
            * Doc B Users -  MMaiden and DOB or Zipcode
            */
            $("#verifydocs").on('click',function(){
                var dob = $("#calendar_inputField").val();
                var zipcode = $("#link_zipcode").val();
                var ssn = $("#ssn-verify").val();
                var mmn = $("#link_maiden").val();
                validateForm();
                //SSN not empty - DOC A Users
                $(".error").remove();
                if( ($("#ssn-verify").val() != null) && ($("#ssn-verify").val() != '') ) {
                    //check DOB is also entered
                    if( ( dob != null) && ( dob != '') ){
                        $("#pinfm").submit();
                    }
                    else {
                        $(".errormsg").html("Please enter DOB");
                        return false
                    }
                }
                else if( ($("#calendar_inputField").val() != null) && ($("#calendar_inputField").val() != '') ){
                    if( ( (ssn != null) && (ssn != '') ) ) {
                        $("#pinfm").submit();
                    } else if(( ( mmn != null) && ( mmn != '') ) ){
                        $("#pinfm").submit();
                    }
                    else{
                        $(".errormsg").html("Please enter either SSN or Mother's Maiden name");
                        return false;
                    }
                }
                else {
                    //DOC B Users
                    if( ($("#link_maiden").val() != null) && ($("#link_maiden").val() != '') ){
                        if( ( (zipcode != null) && (zipcode != '') ) ) {
                            $("#pinfm").submit();

                        } else if(( ( dob != null) && ( dob != '') ) ){
                            $("#pinfm").submit();
                        }else{
                            $(".errormsg").html("Please enter either DOB or Zipcode");
                            return false;
                        }
                    }
                }
                if( ( (zipcode != null) && (zipcode != '') ) ) {
                    if(( ( mmn != null) && ( mmn != '') ) ){
                        $("#pinfm").submit();
                    }
                    else{
                        $(".errormsg").html("Please enter Mother's Maiden Name");
                        return false;
                    }

                }
            });
          function validateForm(){
            var dob = $("#calendar_inputField").val();
            var zipcode = $("#link_zipcode").val();
            var ssn = $("#ssn-verify").val();
            var mmn = $("#link_maiden").val();
              if(dob == '' && zipcode == '' && ssn == '' && mmn == ''){
                  $(".verifymsg_docs").show();
                }else{
                  $(".verifymsg_docs").hide();
              }
          }
     });
</script>
