<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Success</title>
  </head>
  <body>
    <div class="linkaccount-container">
      <div class="linkaccount-inner-container">
        <div class="success-content">
<!--Succes logo-->
          <div class="success-logo">
              <img src="<?php echo $block->getViewFileUrl('images/success.png'); ?>" alt="success icon" />
          </div>
<!--description for success message-->
          <div class="success-description">
            <p>Thank you<br /><span>your curacao card has been linked</span></p>
          </div>
<!--image for curacao card-->
          <div class="card-image">
            <img src="<?php echo $block->getViewFileUrl('images/credit.png'); ?>" alt="Credit image" />
          </div>
<!--description of curacao card holder-->
          <div class="card-description">
            <p>Your Curacao card number:<span> XXXX XXXX 8655 </span></p>
            <p>Name on card:<span> John doe</span></p>
            <p>Expiry date:<span> 02/22</span></p>
          </div>
<!--Button to continue shopping-->
          <div class="button">
            <button type="submit" name="button">Continue Shopping</button>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
