<ul class="header links">
  <li>
    <a href="<?php echo $block->getUrl();?>customer/account/">
      <?php echo __('Your Account');?>
    </a>
  </li>
  <li class="link orders">
    <a href="<?php echo $block->getUrl();?>sales/order/history/">
    <?php echo __('Your orders');?>
    </a>
  </li>
  <li class="authorization-link" data-label="or">
    <a href="<?php echo $block->getUrl();?>customer/account/logout/">
      <?php echo__('Sign Out');?>
    </a>
  </li>
</ul>
