<ul class="header links">
  <li>
    <a href="/customer/account/">
      Your Account
    </a>
  </li>
  <li class="link orders">
    <a href="/sales/order/history/">
    Your orders
    </a>
  </li>
  <li class="link wishlist">
    <a href="/wishlist/">
      Wishlist
    </a>
  </li>
  <li class="authorization-link" data-label="or">
    <a href="/customer/account/logout/">
      Sign Out
    </a>
  </li>
</ul>
