<ul class="header links">
  <li>
    <a href="<?php echo $block->getUrl();?>customer/account/">
      Your Account
    </a>
  </li>
  <li class="link orders">
    <a href="<?php echo $block->getUrl();?>sales/order/history/">
    Your orders
    </a>
  </li>
  <li class="authorization-link" data-label="or">
    <a href="<?php echo $block->getUrl();?>customer/account/logout/">
      Sign Out
    </a>
  </li>
</ul>
