<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
?>
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/** @var Magento\Customer\Block\Account\Customer $block */
?>
<?php if($block->customerLoggedIn()): ?>
    <li class="customer-welcome">
        <span class="customer-name"
              role="link"
              tabindex="0"
              data-mage-init='{"dropdown":{}}'
              data-toggle="dropdown"
              data-trigger-keypress-button="true"
              data-bind="scope: 'customer'"><span class="hello-text">Hello,</span>
            <span class="customer-firstname" data-bind="text:(customer().firstname.length > 7 ? customer().firstname.substring(0, 7) + '...' : customer().firstname)"></span>
            <button type="button"
                    class="action switch"
                    tabindex="-1"
                    data-action="customer-menu-toggle">
                <span><?= $block->escapeHtml(__('Change')) ?></span>
            </button>
        </span>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
        <div class="customer-menu" data-target="dropdown">
            <?php
              echo $this->getLayout()
                        ->createBlock("Magento\Framework\View\Element\Template")
                        ->setTemplate("Magento_Customer::account/customer-menu-dropdown.phtml")
                        ->toHtml();
            ?>
        </div>
    </li>
  <?php else: ?>
    <li class="customer-signin">
      <span class="hello-text">Hello,</span>
          <div class="account-wrapper">
                    <a href="<?php echo $block->getUrl();?>customer/account/login/">
                    <span><?php echo __('Sign in')?></span>
                    </a>
          </div>
    </li>
<?php endif; ?>
