<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;

?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" id="sorterid" for="sorter"><?= /* @escapeNotVerified */ __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?= /* @escapeNotVerified */ $_key ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <!-- horizontal list -->
    <div class="overlay">  <!--black overlay for mobile sorter pop up  --> </div>
    <div class="sorter-list-popup">
      <h3><?= /* @escapeNotVerified */ __('Sort By') ?></h3>
      <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
          <a href="<?php echo $block->getPagerUrl("product_list_order=" . $_key) ?>"
              <?php if ($block->isOrderCurrent($_key)): ?>
                  class="selected"
              <?php endif; ?>
              >
              <?php echo $block->escapeHtml(__($_order)) ?>
          </a>
      <?php endforeach; ?>
      <?php if ($block->getCurrentDirection() == 'desc'): ?>
          <a title="<?= /* @escapeNotVerified */ __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
              <span><?= /* @escapeNotVerified */ __('Set Ascending Direction') ?></span>
          </a>
      <?php else: ?>
          <a title="<?= /* @escapeNotVerified */ __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
              <span><?= /* @escapeNotVerified */ __('Set Descending Direction') ?></span>
          </a>
      <?php endif; ?>
      </div>
</div>
<script>
// On click functionality for sort - Pop up for mobile devices
require([
 'jquery',
   ], function($) {
     (function() {
       var $sortLabel =$('.sorter-label');
       var $sortPopup = $('.sorter-list-popup');
       var $overlay = $('.overlay');
       var width = $(window).width();
       if (width <992) {
         $($sortLabel).unbind('click').click(function(e){
           //open pop up
           $($sortPopup).animate({height: 'toggle'});
           $($overlay).fadeIn( "fast");
           $("body").css({overflow: "hidden"});
          $(".page-header").css({"z-index": "1"});
         });
        $($overlay).unbind('click').click(function(e){
          //close pop up 
          $($sortPopup).animate({height: 'toggle'});
          $($overlay).fadeOut( "fast");
         $("body").css({overflow: "visible"});
         $(".page-header").css({"z-index": "99"});
        });
       }



      })()
});
</script>
