<div class="category-name-widget top-section">
       <!-- sticky anchor for the floating interaction of category list -->
       <!-- <div id="sticky-anchor"></div> -->
         <?php
           $categories = $this->getCategoryCollection();
           $categoryHelper = $this->getCategoryHelper();
           $salecategory= $this->getSaleCategory();
           ?>
       <!-- category list contents -->
       <div class="category-list" id="sticky">
         <div class="title-wrapper">
           <a href="<?= $block->escapeUrl($block->getUrl('clearance-sale')); ?>"><img id="title" src="<?php echo $block->getViewFileUrl('images/sale-title.jpg'); ?>" alt="sales-title"></a>
         </div>
         <div class="list">
           <div class="block-title">
             <img id="icon" src="<?php echo $block->getViewFileUrl('images/sale-icon.jpg'); ?>" alt="sales-icon">
             <!-- widget title -->
             <!-- <h2><?php echo $this->getMainTitle();?></h2> -->
             <h2><?= /* @escapeNotVerified */ __('Sale') ?></h2>
           </div>
           <div class="pn-ProductNav_Wrapper">
             <nav id="pnProductNav" class="pn-ProductNav">
               <div id="pnProductNavContents" class="pn-ProductNav_Contents">
                 <!-- items -->
                    <?php foreach ($categories as $category):
                         $cat = $this->getCategorymodel($category->getId());
                      ?>

                       <a href="<?php echo $block->getUrl('discount_sale/sale/saleproducts', ['category' => $cat->getId(),'sale' => $salecategory ]) ?>" class="pn-ProductNav_Link">
                          <!-- displaying category name -->
                          <?php echo $cat->getName(); ?></a>
                      <?php endforeach; ?>
                       <span id="pnIndicator" class="pn-ProductNav_Indicator"></span>
               </div>
             </nav>
             <button id="pnAdvancerLeft" class="pn-Advancer pn-Advancer_Left" type="button">
               <svg class="pn-Advancer_Icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 551 1024">
                 <path d="M445.44 38.183L-2.53 512l447.97 473.817 85.857-81.173-409.6-433.23v81.172l409.6-433.23L445.44 38.18z" />
               </svg>
             </button>
             <button id="pnAdvancerRight" class="pn-Advancer pn-Advancer_Right" type="button">
               <svg class="pn-Advancer_Icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 551 1024">
                 <path d="M105.56 985.817L553.53 512 105.56 38.183l-85.857 81.173 409.6 433.23v-81.172l-409.6 433.23 85.856 81.174z" />
               </svg>
             </button>
           </div>
         </div>
       </div>
     </div>
