<?php
/**
 * Dyode_curacao theme.
 *
 * Extending Magento_Review
 *
 * @package Dyode
 * @module  Dyode_curacao
 * @author  Rajeev K Tomy <rajeev.ktomy@dyode.com>
 * @copyright Copyright © Dyode
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Product\ReviewRenderer $block */

$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
?>
<?php if ($block->getReviewsCount()): ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <div class="product-reviews-summary short<?= !$rating ? ' no-rating' : '' ?>">
        <?php if ($rating):?>
            <?php $ratingInFive = number_format(($rating/100)*5, 1); ?>
            <div class="rating-summary">
                <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
                <div class="rating"><?= $block->escapeHtml($ratingInFive) ?>*</div>
            </div>
        <?php endif;?>
        <div class="reviews-actions">
            <a class="action view" href="<?= $block->escapeUrl($url) ?>">
                <?= $block->escapeHtml($block->getReviewsCount()) ?>&nbsp;<span><?= ($block->getReviewsCount() == 1) ? $block->escapeHtml(__('Ratings')) : $block->escapeHtml(__('Ratings')) ?></span>
            </a>
        </div>
    </div>
<?php elseif ($block->getDisplayIfEmpty()): ?>
    <div class="product-reviews-summary short empty">
        <div class="reviews-actions">
            <a class="action add" href="<?= $block->escapeUrl($urlForm) ?>">
                <?= $block->escapeHtml(__('Be the first to review this product')) ?>
            </a>
        </div>
    </div>
<?php endif; ?>
