<?php
$this->getTitle();
$value_of_dropdown=$this->getSelectValue();
$classname=$this->getClassNameSingle();
$url=$this->getReferenceUrlSingle();

?>
    <?php $baseurl = $block->getBaseUrl(); ?>
    <?php $mediaUrl = $block->getMediaUrl();?>
<div class="block-products-list">
<div class="content">
  <div class="gateway-playstation-section container">
    <div class="banner-block">
        <?php  $classname = $this->getClassNameSingle(); ?>
        <?php if ($value_of_dropdown == "single") {?>
      <div class="banner-row <?php echo $classname?>">
        <div class="banner-item">
          <!-- single -->
            <?php $desktop_image_single = $this-> getDesktopImageSingle(); ?>
          <!-- displaying desktop image of single  -->
            <?php if ($desktop_image_single != null) :?>
                <?php echo "test"?>
                <?php $desktop_image_single = $mediaUrl . $desktop_image_single;?>
          <a href="<?php echo $url; ?>" class="large"><img src= "<?php echo $desktop_image_single; ?>" alt="<?php "Curacao-banner" ?>" /></a>
            <?php endif;?>
            <?php  $mobile_image_single= $this->getMobileImageSingle(); ?>

          <!-- displaying mobile image -->
            <?php if ($mobile_image_single != null) :?>
                <?php $mobile_image_single = $mediaUrl . $mobile_image_single;?>
          <a  href="<?php echo $url; ?>" class="small"><img src= "<?php echo $mobile_image_single; ?>" alt="<?php "Curacao-banner" ?>" /></a>
            <?php endif;?>
        </div>
      </div>
        <?php } ?>

<!-- double -->
        <?php  $classname_double = $this->getClassNameDouble();
        $url_double_first=$this->getReferenceUrlDoubleFirst();?>
        <?php if ($value_of_dropdown == "double") {?>
      <div class="banner-row <?php echo $classname_double?>">
        <div class="banner-item  ">
            <?php $desktop_image_double_first = $this-> getDesktopImageDoubleFirst();?>
          <!-- displaying desktop image -->
            <?php if ($desktop_image_double_first!= null) :?>
                <?php $desktop_image_double_first = $mediaUrl . $desktop_image_double_first;?>
          <a href="<?php echo $url_double_first; ?>" class="large"><img src= "<?php echo $desktop_image_double_first; ?>"alt="<?php "Curacao-banner" ?>" /></a>
            <?php endif;?>
           <!-- displaying mobile image -->
            <?php $mobile_image_double_first= $this->getMobileImageDoubleFirst();?>
            <?php $mobile_image_double_first =  $mediaUrl . $mobile_image_double_first;?>
            <?php if ($mobile_image_double_first != null) :?>
             <a  href="<?php echo $url_double_first; ?>" class="small"><img src= "<?php echo $mobile_image_double_first; ?>"alt="<?php "Curacao-banner" ?>" /></a>
            <?php endif;?>
        </div>
        <div class="banner-item">
            <?php $url_double_second=$this->getReferenceUrlDoubleSecond();
            $desktop_image_double_second = $this-> getDesktopImageDoubleSecond();?>
            <?php $desktop_image_double_second =  $mediaUrl . $desktop_image_double_second;?>
          <!--displaying desktop image  -->
            <?php if ($desktop_image_double_second != null) :?>
          <a href="<?php echo $url_double_second; ?>" class="large">
            <img src= "<?php echo $desktop_image_double_second; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
          <?php endif;?>
            <?php $mobile_image_double_second= $this->getMobileImageDoubleSecond();?>
            <?php $mobile_image_double_second =  $mediaUrl . $mobile_image_double_second;?>
          <!-- displaying mobile image -->
          <?php if ($mobile_image_double_second != null) :?>
          <a  href="<?php echo $url_double_second; ?>" class="small"><img src= "<?php echo $mobile_image_double_second; ?>"alt="<?php "Curacao-banner" ?>" /></a>
        <?php endif;?>
        </div>
      </div>
        <?php }?>

<!--triple  -->


        <?php  $classname_triple = $this->getClassNameTriple();
             $url_triple_first= $this->getReferenceUrlTripleFirst();?>
        <?php if ($value_of_dropdown=="triple") {?>
      <div class="banner-row <?php echo $classname_triple?>">
            <?php if ($classname_triple=="three-image-grid") :?>
                <?php $first_image_class = 'banner-item left'?>
            <?php else :?>
          <?php $first_image_class = 'banner-item'?>
            <?php endif ?>
        <div class="<?php echo $first_image_class;?>">
            <?php $desktop_image_triple_first = $this->getDesktopImageTripleFirst();?>
            <?php $desktop_image_triple_first = $mediaUrl . $desktop_image_triple_first;?>
            <!-- desktop image for triple -->
            <?php if ($desktop_image_triple_first != null) :?>
          <a href="<?php echo $url_triple_first; ?>" class="large">
            <img src="<?php echo $desktop_image_triple_first; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
            <?php endif;?>
          <!-- mobile image for triple -->
            <?php $mobile_image_triple_first= $this->getMobileImageTripleFirst(); ?>
            <?php $mobile_image_triple_first = $mediaUrl . $mobile_image_triple_first;?>
            <?php if ($mobile_image_triple_first != null) :?>
          <a href="<?php echo $url_triple_first; ?>" class="small">
              <img src="<?php echo $mobile_image_triple_first; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
          <?php endif;?>
        </div>

        <!-- <div class="banner-item right"> -->
            <?php if ($classname_triple=="three-image-grid") :?>
          <div class="banner-item right">
            <?php endif ?>
          <div class="banner-item">
            <?php
            $url_triple_second=$this->getReferenceUrlTripleSecond();
            $desktop_image_triple_second = $this-> getDesktopImageTripleSecond();?>
            <?php $desktop_image_triple_second =  $mediaUrl . $desktop_image_triple_second;?>
            <?php if ($desktop_image_triple_second  != null) :?>
          <a href="<?php echo $url_triple_second; ?>" class="large">
            <img src= "<?php echo $desktop_image_triple_second; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
            <?php endif;?>
          <!-- displaying mobile for triple -->
            <?php $mobile_image_triple_second= $this->getMobileImageTripleSecond(); ?>
            <?php $mobile_image_triple_second =  $mediaUrl . $mobile_image_triple_second;?>
            <?php if ($mobile_image_triple_second  != null) :?>
          <a href="<?php echo $url_triple_second; ?>" class="small">
              <img src= "<?php echo $mobile_image_triple_second; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
          <?php endif;?>
         </div>
          <div class="banner-item">
            <?php
            $url_triple_third =$this->getReferenceUrlTripleThird();
            $desktop_image_triple_third = $this-> getDesktopImageTripleThird();?>
            <?php $desktop_image_triple_third =  $mediaUrl . $desktop_image_triple_third;?>
            <?php if ($desktop_image_triple_third  != null) :?>
          <a href="<?php echo $url_triple_third; ?>" class="large">
            <img src= "<?php echo $desktop_image_triple_third; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
          <?php endif;?>
            <?php $mobile_image_triple_third= $this->getMobileImageTripleThird();?>
            <?php $mobile_image_triple_third =  $mediaUrl . $mobile_image_triple_third;?>
            <?php if ($desktop_image_triple_third  != null) :?>
          <a href="<?php echo $url_triple_third; ?>" class="small">
            <img src= "<?php echo $mobile_image_triple_third; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
          <?php endif;?>
      </div>
            <?php if ($classname_triple=="three-image-grid") :?>
      </div>
            <?php endif ?>
    </div>
        <?php }?>

<!-- quadruple -->

        <?php  $classname_quadruple = $this->getClassNameQuadruple();
              $url_quadruple_one= $this->getReferenceUrlquadrupleFirst();
        ?>
        <?php if ($value_of_dropdown== "quadruple") {?>
      <div class="banner-row <?php echo $classname_quadruple?>">
        <div class="banner-item">
            <?php $desktop_image_quadruple_first = $this-> getDesktopImagequadrupleFirst();?>
            <?php $desktop_image_quadruple_first =  $mediaUrl . $desktop_image_quadruple_first;?>
            <?php if ($desktop_image_quadruple_first != null) :?>
            <a href="<?php echo $url_quadruple_one; ?>" class="large">
            <img src= "<?php echo $desktop_image_quadruple_first; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
        <?php endif;?>
            <?php
            $mobile_image_quadruple_first= $this-> getMobileImagequadrupleFirst();?>
            <?php $mobile_image_quadruple_first =  $mediaUrl . $mobile_image_quadruple_first;?>
            <?php if ($mobile_image_quadruple_first  != null) :?>
          <a href="<?php echo $url_quadruple_one; ?>" class="small">
            <img src= "<?php echo $mobile_image_quadruple_first; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
        <?php endif;?>
        </div>
        <div class="banner-item">
            <?php
            $url_quadruple_second= $this->getReferenceUrlquadrupleSecond();
            $desktop_image_quadruple_second = $this-> getDesktopImagequadrupleSecond();?>
            <?php $desktop_image_quadruple_second =  $mediaUrl . $desktop_image_quadruple_second;?>
            <?php if ($desktop_image_quadruple_second  != null) :?>
          <a href="<?php echo $url_quadruple_second; ?>" class="large">
          <img src= "<?php echo $desktop_image_quadruple_second; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
        <?php endif;?>
            <?php
            $mobile_image_quadruple_second= $this->getMobileImagequadrupleSecond();
            ?>
            <?php $mobile_image_quadruple_second =  $mediaUrl . $mobile_image_quadruple_second;?>
            <?php if ($mobile_image_quadruple_second  != null) :?>
          <a href="<?php echo $url_quadruple_second; ?>" class="small">
            <img src= "<?php echo $mobile_image_quadruple_second; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
        <?php endif;?>
        </div>
        <div class="banner-item">
            <?php
            $url_quadruple_third=$this->getReferenceUrlquadrupleThird();
            $desktop_image_quadruple_third = $this-> getDesktopImagequadrupleThird();?>
            <?php $desktop_image_quadruple_third =  $mediaUrl . $desktop_image_quadruple_third;?>
            <?php if ($desktop_image_quadruple_third  != null) :?>
          <a href="<?php echo $url_quadruple_third; ?>" class="large">
          <img src= "<?php echo $desktop_image_quadruple_third; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
        <?php endif;?>
            <?php
            $mobile_image_quadruple_third= $this->getMobileImagequadrupleThird();
            ?>
            <?php $mobile_image_quadruple_third =  $mediaUrl . $mobile_image_quadruple_third;?>
            <?php if ($mobile_image_quadruple_third != null) :?>
          <a href="<?php echo $url_quadruple_third; ?>" class="small">
            <img src= "<?php echo $mobile_image_quadruple_third; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
        <?php endif;?>
        </div>
        <div class="banner-item">
            <?php
            $url_quadruple_fourth =$this->getReferenceUrlquadrupleFourth();
            $desktop_image_quadruple_fourth = $this-> getDesktopImagequadrupleFourth();?>
            <?php $desktop_image_quadruple_fourth =  $mediaUrl . $desktop_image_quadruple_fourth;?>
            <?php if ($desktop_image_quadruple_fourth != null) :?>
          <a href=<?php echo $url_quadruple_fourth; ?>"" class="large">
          <img src= "<?php echo $desktop_image_quadruple_fourth; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
        <?php endif;?>
            <?php
            $mobile_image_quadruple_fourth= $this->getMobileImagequadrupleFourth();
            ?>
            <?php $mobile_image_quadruple_fourth =  $mediaUrl . $mobile_image_quadruple_fourth;?>
            <?php if ($mobile_image_quadruple_fourth != null) :?>
          <a href="<?php echo $url_quadruple_fourth; ?>" class="small">
            <img src= "<?php echo $mobile_image_quadruple_fourth; ?>"alt="<?php "Curacao-banner" ?>" />
          </a>
        <?php endif;?>
        </div>
      </div>
        <?php }?>
    </div>
  </div>
</div>
</div>
