<?php
$this->getTitle();
$value_of_dropdown=$this->getSelectValue();
$classname=$this->getClassNameSingle();
$url=$this->getReferenceUrlSingle();
?>
<div class="content">
  <div class="gateway-playstation-section container">
    <div class="banner-block">
      <?php  $classname = $this->getClassNameSingle(); ?>
      <?php if($value_of_dropdown == "single"){?>
      <div class="banner-row <?php echo $classname?>">
        <div class="banner-item">
          <!-- single -->
          <?php $desktop_image_single = $this-> getDesktopImageSingle(); ?>
          <!-- displaying desktop image -->
          <a href="<?php echo $url; ?>" class="large"><img src= "<?php echo $desktop_image_single; ?>" alt="<?php "abc" ?>" /></a>
          <?php  $mobile_image_single= $this->getMobileImageSingle(); ?>
          <!-- displaying mobile image -->
          <a  href="<?php echo $url; ?>" class="small"><img src= "<?php echo $mobile_image_single; ?>" alt="<?php "abcd" ?>" /></a>
        </div>
      </div>
    <?php } ?>

<!-- double -->
      <?php  $classname_double = $this->getClassNameDouble();
      $url_double_first=$this->getReferenceUrlDoubleFirst();?>
       <?php if($value_of_dropdown == "double"){?>
      <div class="banner-row <?php echo $classname_double?>">
        <div class="banner-item  ">
          <?php $desktop_image_double_first = $this-> getDesktopImageDoubleFirst();?>
          <!-- displaying desktop image -->
          <a href="<?php echo $url_double_first; ?>" class="large"><img src= "<?php echo $desktop_image_double_first; ?>"alt="<?php "abc" ?>" /></a>
          <?php $mobile_image_double_first= $this->getMobileImageDoubleFirst();?>
          <!-- displaying mobile image -->
          <a  href="<?php echo $url_double_first; ?>" class="small"><img src= "<?php echo $mobile_image_double_first; ?>"alt="<?php "abcd" ?>" /></a>
        </div>
        <div class="banner-item">
          <?php $url_double_second=$this->getReferenceUrlDoubleSecond();
          $desktop_image_double_second = $this-> getDesktopImageDoubleSecond();?>
          <!--displaying desktop image  -->
          <a href="<?php echo $url_double_second; ?>" class="large">
            <img src= "<?php echo $desktop_image_double_second; ?>"alt="<?php "abc" ?>" />
          </a>
          <?php $mobile_image_double_second= $this->getMobileImageDoubleSecond();?>
          <!-- displaying mobile image -->
          <a  href="<?php echo $url_double_second; ?>" class="small"><img src= "<?php echo $mobile_image_double_second; ?>"alt="<?php "abcd" ?>" /></a>
        </div>
      </div>
    <?php }?>

<!--triple  -->


      <?php  $classname_triple = $this->getClassNameTriple();
             $url_triple_first= $this->getReferenceUrlTripleFirst();?>
      <?php if ($value_of_dropdown=="triple"){?>
      <div class="banner-row <?php echo $classname_triple?>">
        <div class="banner-item  ">
          <?php $desktop_image_triple_first = $this-> getDesktopImageTripleFirst();?>
          <a href="<?php echo $url_triple_first; ?>" class="large">
            <img src="<?php echo $desktop_image_triple_first; ?>"alt="<?php "abc" ?>" />
          </a>
          <?php $mobile_image_triple_first= $this-> getMobileImageTripleFirst(); ?>
          <a href="<?php echo $url_triple_first; ?>" class="small">
              <img src="<?php echo $mobile_image_triple_first; ?>"alt="<?php "abcd" ?>" />
          </a>
        </div>

        <div class="banner-item">
          <?php
           $url_triple_second=$this->getReferenceUrlTripleSecond();
           $desktop_image_triple_second = $this-> getDesktopImageTripleSecond();?>
          <a href="<?php echo $url_triple_second; ?>" class="large">
            <img src= "<?php echo $desktop_image_triple_second; ?>"alt="<?php "abc" ?>" />
          </a>
          <?php $mobile_image_triple_second= $this->getMobileImageTripleSecond(); ?>
          <a href="<?php echo $url_triple_second; ?>" class="small">
              <img src= "<?php echo $mobile_image_triple_second; ?>"alt="<?php "abcd" ?>" />
          </a>
        </div>
        <div class="banner-item">
          <?php
          $url_triple_third =$this->getReferenceUrlTripleThird();
          $desktop_image_triple_third = $this-> getDesktopImageTripleThird();?>
          <a href="<?php echo $url_triple_third; ?>" class="large">
            <img src= "<?php echo $desktop_image_triple_third; ?>"alt="<?php "abc" ?>" />
          </a>
         <?php $mobile_image_triple_third= $this->getMobileImageTripleThird();?>
          <a href="<?php echo $url_triple_third; ?>" class="small">
            <img src= "<?php echo $mobile_image_triple_third; ?>"alt="<?php "abcd" ?>" />
          </a>
        </div>
      </div>
<?php }?>

<!-- quadruple -->

      <?php  $classname_quadruple = $this->getClassNameQuadruple();
              $url_quadruple_one= $this->getReferenceUrlquadrupleFirst();
       ?>
      <?php if($value_of_dropdown== "quadruple"){?>
      <div class="banner-row <?php echo $classtriple?>">
        <div class="banner-item">
          <?php $desktop_image_quadruple_first = $this-> getDesktopImagequadrupleFirst();?>
            <a href="<?php echo $url_quadruple_one; ?>" class="large">
            <img src= "<?php echo $desktop_image_quadruple_first; ?>"alt="<?php "abc" ?>" />
          </a>
          <?php
          $mobile_image_quadruple_first= $this-> getMobileImagequadrupleFirst();
          ?>
          <a href="<?php echo $url_quadruple_one; ?>" class="small">
            <img src= "<?php echo $mobile_image_quadruple_first; ?>"alt="<?php "abcd" ?>" />
          </a>
        </div>
        <div class="banner-item">
          <?php
          $url_quadruple_second= $this->getReferenceUrlquadrupleSecond();
          $desktop_image_quadruple_second = $this-> getDesktopImagequadrupleSecond();?>
          <a href="<?php echo $url_quadruple_second; ?>" class="large">
          <img src= "<?php echo $desktop_image_quadruple_second; ?>"alt="<?php "abc" ?>" />
          </a>
          <?php
          $mobile_image_quaruple_second= $this->getMobileImagequadrupleSecond();
          ?>
          <a href="<?php echo $url_quadruple_second; ?>" class="small">
            <img src= "<?php echo $mobile_image_quaruple_second; ?>"alt="<?php "abcd" ?>" />
          </a>
        </div>
        <div class="banner-item">
      <?php
      $url_quadruple_third=$this->getReferenceUrlquadrupleThird();
      $desktop_image_quadruple_third = $this-> getDesktopImagequadrupleThird();?>
          <a href="<?php echo $url_quadruple_third; ?>" class="large">
          <img src= "<?php echo $desktop_image_quadruple_third; ?>"alt="<?php "abc" ?>" />
          </a>
          <?php
          $mobile_image_quadruple_third= $this->getMobileImagequadrupleThird();
          ?>
          <a href="<?php echo $url_quadruple_third; ?>" class="small">
            <img src= "<?php echo $mobile_image_quadruple_third; ?>"alt="<?php "abcd" ?>" />
          </a>
        </div>
        <div class="banner-item">
      <?php
       $url_quadruple_fourth =$this->getReferenceUrlquadrupleFourth();
       $desktop_image_quadruple_fourth = $this-> getDesktopImagequadrupleFourth();?>
          <a href=<?php echo $url_quadruple_fourth; ?>"" class="large">
          <img src= "<?php echo $desktop_image_quadruple_fourth; ?>"alt="<?php "abc" ?>" />
          </a>
          <?php
          $mobile_image_quadruple_fourth= $this->getMobileImagequadrupleFourth();
          ?>
          <a href="<?php echo $url_quadruple_fourth; ?>" class="small">
            <img src= "<?php echo $mobile_image_quadruple_fourth; ?>"alt="<?php "abcd" ?>" />
          </a>
        </div>
      </div>
<?php }?>
    </div>
  </div>
</div>
