<?php
echo $this->getTitle();
echo $this->getSelectValue();
echo $this->getClassNameSingle();
echo $this->getReferenceUrlSingle();
//single
 $desktop_image = $this-> getDesktopImageSingle();?>
 <a href="#">
<img src= "<?php echo $desktop_image; ?>"alt="<?php "abc" ?>" />
</a>
<?php
$mobile_image= $this->getMobileImageSingle();
?>
<a  href="#">
<img src= "<?php echo $mobile_image; ?>"alt="<?php "abcd" ?>" />
</a>
<!-- double first -->
<?php
echo $this->getClassNameDouble();
echo $this->getReferenceUrlDoubleFirst();
$desktop_image = $this-> getDesktopImageDoubleFirst();?>
<a href="#">
<img src= "<?php echo $desktop_image; ?>"alt="<?php "abc" ?>" />
</a>
<?php
$mobile_image= $this->getMobileImageDoubleFirst();
?>
<a  href="#">
<img src= "<?php echo $mobile_image; ?>"alt="<?php "abcd" ?>" />
</a>
<!-- second image for double option -->
<?php
echo $this->getReferenceUrlDoubleSecond();
$desktop_image = $this-> getDesktopImageDoubleSecond();?>
<a href="#">
<img src= "<?php echo $desktop_image; ?>"alt="<?php "abc" ?>" />
</a>
<?php
$mobile_image= $this->getMobileImageDoubleSecond();
?>
<a  href="#">
<img src= "<?php echo $mobile_image; ?>"alt="<?php "abcd" ?>" />
</a>
<!-- triple first -->
<?php
echo $this->getClassNameTriple();
echo $this->getReferenceUrlTripleFirst();
$desktop_image = $this-> getDesktopImageTripleFirst();?>
<a href="#">
<img src= "<?php echo $desktop_image; ?>"alt="<?php "abc" ?>" />
</a>
<?php
$mobile_image= $this-> getMobileImageTripleFirst();
?>
<a  href="#">
<img src= "<?php echo $mobile_image; ?>"alt="<?php "abcd" ?>" />
</a>
<!-- second image for triple option -->
<?php
echo $this->getReferenceUrlTripleSecond();
$desktop_image = $this-> getDesktopImageTripleSecond();?>
<a href="#">
<img src= "<?php echo $desktop_image; ?>"alt="<?php "abc" ?>" />
</a>
<?php
$mobile_image= $this->getMobileImageTripleSecond();
?>
<a  href="#">
<img src= "<?php echo $mobile_image; ?>"alt="<?php "abcd" ?>" />
</a>
<!-- third image for triple option -->
<?php
echo $this->getReferenceUrlTripleThird();
$desktop_image = $this-> getDesktopImageTripleThird();?>
<a href="#">
<img src= "<?php echo $desktop_image; ?>"alt="<?php "abc" ?>" />
</a>
<?php
$mobile_image= $this->getMobileImageTripleThird();
?>
<a  href="#">
<img src= "<?php echo $mobile_image; ?>"alt="<?php "abcd" ?>" />
</a>
<!-- quadruple first -->
<?php
echo $this->getClassNameQuadruple();
echo $this->getReferenceUrlquadrupleFirst();
$desktop_image = $this-> getDesktopImagequadrupleFirst();?>
<a href="#">
<img src= "<?php echo $desktop_image; ?>"alt="<?php "abc" ?>" />
</a>
<?php
$mobile_image= $this-> getMobileImagequadrupleFirst();
?>
<a  href="#">
<img src= "<?php echo $mobile_image; ?>"alt="<?php "abcd" ?>" />
</a>
<!-- second image for quadruple option -->
<?php
echo $this->getReferenceUrlquadrupleSecond();
$desktop_image = $this-> getDesktopImagequadrupleSecond();?>
<a href="#">
<img src= "<?php echo $desktop_image; ?>"alt="<?php "abc" ?>" />
</a>
<?php
$mobile_image= $this->getMobileImagequadrupleSecond();
?>
<a  href="#">
<img src= "<?php echo $mobile_image; ?>"alt="<?php "abcd" ?>" />
</a>
<!-- third image for triple option -->
<?php
echo $this->getReferenceUrlquadrupleThird();
$desktop_image = $this-> getDesktopImagequadrupleThird();?>
<a href="#">
<img src= "<?php echo $desktop_image; ?>"alt="<?php "abc" ?>" />
</a>
<?php
$mobile_image= $this->getMobileImagequadrupleThird();
?>
<a  href="#">
<img src= "<?php echo $mobile_image; ?>"alt="<?php "abcd" ?>" />
</a>
<!-- fourth image for triple option -->
<?php
echo $this->getReferenceUrlquadrupleFourth();
$desktop_image = $this-> getDesktopImagequadrupleFourth();?>
<a href="#">
<img src= "<?php echo $desktop_image; ?>"alt="<?php "abc" ?>" />
</a>
<?php
$mobile_image= $this->getMobileImagequadrupleFourth();
?>
<a  href="#">
<img src= "<?php echo $mobile_image; ?>"alt="<?php "abcd" ?>" />
</a>
