<?php
/**
 * Dyode_curacao theme.
 *
 * Extending Magento_Catalog
 *
 * @package Dyode
 * @module  Dyode_curacao
 * @author  Rajeev K Tomy <rajeev.ktomy@dyode.com>
 * @copyright Copyright © Dyode
 */

// @codingStandardsIgnoreFile
?>

<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 * @var $viewModel \Dyode\Core\ViewModel\Emi
 */
$viewModel = $block->getViewModel();
$emi = $viewModel->monthlyEmi($block->getProduct()->getFinalPrice());
$helper = $viewModel->helper();
?>

<?php if ($emi): ?>
<div class="credit-card-desc">
    <img src="<?php echo $this->getViewFileUrl('images/price-tag.png'); ?>" />
    <?= __('Or as low as ') ?>
    <span class="emi-amount">
        <?= $block->escapeHtml($helper->formatPrice($emi)); ?>/<?= __('month'); ?>
    </span>
</div>
<div class="credti-card-apply">
    <a href="#" class="credit-link"><?= __('Apply for Curacao credit card'); ?></a>
</div>
<?php endif; ?>