<script type='text/x-magento-init'>
 var ccs_cc_args = ccs_cc_args || [];
 var CPN = <?php $block->getProduct()getSku();?>

 // Product Page
 ccs_cc_args.push(['cpn', 'CPN']);
 // ccs_cc_args.push(['mf', 'MANUFACTURER_NAME']);
 // ccs_cc_args.push(['pn', 'MANUFACTURER_PART_NUMBER']);
 ccs_cc_args.push(['upcean', 'UPC_EAN_CODE']);
 ccs_cc_args.push(['ccid', 'CATALOG_CODE']);
 ccs_cc_args.push(['lang', 'EN']);
 ccs_cc_args.push(['market', 'US']);

 (function () {
 var o = ccs_cc_args; o.push(['_SKey', 'b6d81391']); o.push(['_ZoneId', 'bef7a93fe8']);
 var sc = document.createElement('script'); sc.type = 'text/javascript'; sc.async = true;
 sc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.cnetcontent.com/jsc/h.js';
 var n = document.getElementsByTagName('script')[0]; n.parentNode.insertBefore(sc, n);
 })();
 </script>
