<?php
/**
* @var \Magento\Catalog\Block\Product\View $block
* @var \Magento\Catalog\Model\Product $_product
*/
$_product = $block->getProduct();
$_tvBrandText = '';
$_upcText = '';

/**
* @todo Better use a view model here to implement this logic
*/
if ($_product->getResource()->getAttribute('tv_brand')) {
$_tvBrandText = $_product->getAttributeText('tv_brand');
}

if ($_product->getUpc()) {
$_upcText = $_product->getUpc();
}
?>
<?php $getMpn = explode("-",$_product->getSku()); 
	$mpn = $getMpn[2];
?>
<script type='text/javascript'>

var ccs_cc_args = ccs_cc_args || [];
// Product Page
ccs_cc_args.push(['cpn', '<?php echo $_product->getEntityId();?>']);
ccs_cc_args.push(['mf', ' <?php echo $_tvBrandText; ?>']);
ccs_cc_args.push(['pn', '<?php echo $mpn; ?>']);
ccs_cc_args.push(['upcean', '<?php $_upcText; ?>']);
ccs_cc_args.push(['ccid', 'CATALOG_CODE']);
ccs_cc_args.push(['lang', 'EN']);
ccs_cc_args.push(['market', 'US']);
(function () {
var o = ccs_cc_args; o.push(['_SKey', 'b6d81391']); o.push(['_ZoneId', 'bef7a93fe8']);
var sc = document.createElement('script'); sc.type = 'text/javascript'; sc.async = true;
sc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.cnetcontent.com/jsc/h.js';
var n = document.getElementsByTagName('script')[0]; n.parentNode.insertBefore(sc, n);
})();
</script>
<div id="ccs-feature-icons"></div>
<div id="ccs-logos"></div>
<div id="ccs-explore-product"></div>
<div id="ccs-inline-content">
