<div class="slider-title">
  <h2 class='widget-title'>Similar products selling fast</h2>
</div>
<div class="owl-carousel out-of-stock-carousel">
<div class="item">
        <a href="http://icuracao.local/catalog/product/view/id/68338/">
                                      <div class="productimage-container">
            <img src="http://icuracao.local/pub/static/version1542615548/frontend/Dyode/curacao/en_US/Magento_Catalog/images/product/placeholder/image.jpg" alt="product">
          </div>
            <h3>BestHome PF14CRN1BH 14000 BTU Portable Air Conditioner</h3>
              <p class="price">

                                              <span class="discount-price">
                  $429.99                </span>
                              </p>

                <p class="subtext">Or as low as    <span class="amount emi-amount">
    $43.00/month   </span>
 </p>
          </a>
      </div>
      <div class="item">
        <a href="http://icuracao.local/catalog/product/view/id/78127/">
                                      <div class="productimage-container">
            <img src="http://icuracao.local/pub/static/version1542615548/frontend/Dyode/curacao/en_US/Magento_Catalog/images/product/placeholder/image.jpg" alt="product">
          </div>
            <h3>LG 49UK6300 LED 49" / 4K UHD / 60Hz HDR Smart TV With AI ThinQ - Black</h3>
              <p class="price">

                                              <span class="discount-price">
                  $499.95                </span>
                              </p>

                <p class="subtext">Or as low as    <span class="amount emi-amount">
    $50.00/month   </span>
 </p>
          </a>
      </div>
      <div class="item">
        <a href="http://icuracao.local/catalog/product/view/id/78657/">
                                      <div class="productimage-container">
            <img src="http://icuracao.local/pub/static/version1542615548/frontend/Dyode/curacao/en_US/Magento_Catalog/images/product/placeholder/image.jpg" alt="product">
          </div>
            <h3>HP HP15DA0074NR Laptop 15.6" / 4GB/16GB RAM / 1TB HDD Intel Core i3-7020U Dual Core 2.3GHz  Processor - Black</h3>
              <p class="price">

                                              <span class="discount-price">
                  $479.99                </span>
                              </p>

                <p class="subtext">Or as low as    <span class="amount emi-amount">
    $48.00/month   </span>
 </p>
          </a>
      </div>
      <div class="item">
        <a href="http://icuracao.local/catalog/product/view/id/78924/">
                                      <div class="productimage-container">
            <img src="http://icuracao.local/pub/static/version1542615548/frontend/Dyode/curacao/en_US/Magento_Catalog/images/product/placeholder/image.jpg" alt="product">
          </div>
            <h3>HP Deskjet All-In-One Printer- White</h3>
              <p class="price">

                                              <span class="discount-price">
                  $69.99                </span>
                              </p>

                <p class="subtext">Or as low as    <span class="amount emi-amount">
    $20.00/month   </span>
 </p>
          </a>
      </div>
      <div class="item">
        <a href="http://icuracao.local/catalog/product/view/id/78930/">
                                      <div class="productimage-container">
            <img src="http://icuracao.local/pub/static/version1542615548/frontend/Dyode/curacao/en_US/Magento_Catalog/images/product/placeholder/image.jpg" alt="product">
          </div>
            <h3>Samsung Galaxy Note9 6.4" / 128GB Unlocked Smartphone - Ocean Blue - Pre-Order</h3>
              <p class="price">

                                              <span class="discount-price">
                  $999.99                </span>
                              </p>

                <p class="subtext">Or as low as    <span class="amount emi-amount">
    $75.00/month   </span>
 </p>
          </a>
      </div></div>
      <script type="text/x-magento-init">
          {
          ".out-of-stock-carousel": {
              "OwlCarousel": {
                "dots":false,
                "loop": false,
                "nav":true,
                "margin": 0,
                "navText": ["<div class='custom-prev'><div class='left'></div></div>", "<div class='custom-next'><div class='right'></div></div>"],
                "responsive": {
                  "0": {
                    "items": 1,
                    "stagePadding":40
                  },
                  "400": {
                    "items": 2,
                    "stagePadding":40
                  },
                  "768": {
                    "items": 3
                  },
                  "1045": {
                    "items": 4
                  }
                }
              }
            }
          }
      </script>
