<?php
/**
 * Dyode_curacao theme.
 *
 * Extending Magento_Catalog
 *
 * @package Dyode
 * @module  Dyode_curacao
 * @author  Rajeev K Tomy <rajeev.ktomy@dyode.com>
 * @copyright Copyright © Dyode
 */

/**
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>

<?php if ($block->hasOptions()):?>
<div id="warrantyModal">
    <div class="product-details">
        <h4><?= $block->getProduct()->getName() ?></h4>
        <p><?= __('Model') ?> #<?= $block->getProduct()->getSku() ?></p>
        <?= $block->getChildHtml('warranty.modal.review'); ?>
    </div>
    <div class="warranty-options">
        <?= $block->getChildHtml('product_options_wrapper') ?>
    </div>
    <div class="bottom">
        <a
                href="<?= $block->getUrl('checkout/cart'); ?>"
                style="display:none"
                id="warranty-go-to-cart-link">
            <?=  __('Go to Cart'); ?>
        </a>
    </div>

</div>
<?php endif ?>
