<form id="interestbeat" class="form" action="<?= $block->getUrl('interestbeat/user/post',['_secure' => $this->getRequest()->isSecure()]);?>" method="post" enctype="multipart/form-data">
    <fieldset class="fieldset">
      <p class="title"><span><?php /* @escapeNotVerified */ echo __('Interest Beat') ?></span></p>
      <p class="title-desc"><span><?php /* @escapeNotVerified */ echo __("We'll Beat any Competitor's Prices") ?></span></p>

      <div class="field required firstName-box">
          <div class="control">
              <input type="text" id="first_name" name="first_name"  placeholder=<?php echo __('First Name')?> class="input-text"/>
          </div>
      </div>
      <div class="field required lastName-box">
          <div class="control">
              <input type="text" id="last_name" name="last_name" placeholder=<?php echo __('Last Name')?> class="input-text"/>
          </div>
      </div>
      <div class="field required email-box">
          <div class="control">
              <input type="email" id="email" name="email" placeholder=<?php echo __('Email')?> class="input-text"/>
          </div>
      </div>
      <div class="field required phoneNum-box">
          <div class="control">
              <input type="number" id="phonenumber" name="phonenumber" placeholder=<?php echo __('Phone Number')?> class="input-text"/>
          </div>
      </div>
      <div class="field required accNum-box">
          <div class="control">
              <input type="number" id="account_number" name="account_number" placeholder=<?php echo __('Account Number')?> class="input-text"/>
          </div>
      </div>
      <div class="field required invoiceNum-box">
          <div class="control">
              <input type="number" id="invoice_number" name="invoice_number" placeholder=<?php echo __('Invoice/Order Number')?> class="input-text"/>
          </div>
      </div>

      <p class="prod-info"><span><?php /* @escapeNotVerified */ echo __('Please provide us with the product information with one of the following options') ?></span></p>


      <div class="control competitor-link">
          <input type="url" id="product_url" name="product_url" placeholder="<?php echo __("Competitor's product link")?>" class="input-text"/>
      </div>

      <div class="or-block">
        <p class="line"></p>
        <p class="or-text">OR</p>
      </div>


      <label for="productimage" class="label"><span><?php /* @escapeNotVerified */ echo __("Competitor's product image or screenshot") ?></span></label>
      <!-- <div class="control uploadFile-box">
        <input type="file" name="upload_file" class="input-text upload"/>
        <label for="file">Choose file</label>
      </div> -->
      <div class="curacao-file-upload">
        <div class="file-upload">
          <div class="file-select">
            <div class="file-select-button" id="fileName"><?php echo __('Choose File')?></div>
            <div class="file-select-name" id="noFile"><?php echo __('No file chosen')?></div>
            <input type="file" name="upload_file" id="chooseFile">
          </div>
        </div>
      </div>


      <div class="actions-toolbar">
          <div class="primary">
              <button  id="interestbeat-btn" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                  <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
              </button>
          </div>
      </div>
    </fieldset>
</form>

<div class="beat-banner interest-beat-banner">
   <div class="beat-logo">
     <img src="<?php echo $this->getViewFileUrl('images/interestbeat_logo.png'); ?>" alt="Price Beat Logo">
   </div>
   <div class="beat-banner-content">
     <h3><?php echo __('We will beat any competitors');?> <br> <?php echo __('INTEREST RATE');?></h3>
     <p><?php echo __('Curacao is so confident in our landing practices and the interest
       rate that we offer, We have introduced our INTEREST BEAT GUARANTEE.
       This ensures that our cunsomers can enhoy better interest rates than
       you are able to get with any other retailer’s store credit card.');?></p>
      <p><?php echo __('Curacao continually reviews its lending rates and tries to ensure
        that our customers pay competitive rate on their outstanding debt.
        With Curacao’s INTEREST BEAT GUARANTEE, We will not only match
        the competitor’s interest rate, but we will BEAT it! That is our promise.');?></p>
   </div>
 </div>

<script type="text/javascript">
require([
  'jquery'
], function($) {$(function() {
  $('#interestbeat-btn').on('click', function(e) {
    e.preventDefault();
    var productlink    = $('#product_url').val();
    var product_image  = $('input[name=upload_file]').val();
    var first_name     = $('#first_name').val();
    var last_name      =$('#last_name').val();
    var email          =$('#email').val();
    var phonenumber    =$('#phonenumber').val();
    var account_number =$('#account_number').val();
    var invoice_number =$('#invoice_number').val();
    var numericExpression = /^\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i;

    $(".error").remove();
    if(first_name== ""){
      $('#first_name').after('<span class="error"><?php echo __('First name is required')?></span>');
    }
    if(last_name== ""){
      $('#last_name').after('<span class="error"><?php echo __('Last name is required')?></span>');
    }
    if(email== ""){
        $('#email').after('<span class="error"><?php echo __('Email-id is required')?></span>');
    }
      else {
        if(!numericExpression.test(email)){
          $('#email').after('<span class="error"><?php echo __('Email-id invalid')?></span>');
        }
      }
    if(phonenumber== ""){
      $('#phonenumber').after('<span class="error"><?php echo __('Phone number is required')?></span>');
    }

    if(invoice_number== ""){
      $('#invoice_number').after('<span class="error"><?php echo __('Invoice number is required')?></span>');
    }
    if (productlink == "" && product_image == "") {
        $('#product_url').after('<span class="error"><?php echo __('Product Link or Product Image is required')?></span>');
    } else {
      $('#interestbeat').submit();

    }

  });
});
});

</script>


<script>
require([
  'jquery'
], function($) {$(function() {

$('#chooseFile').bind('change', function () {
  var filename = $("#chooseFile").val();
  if (/^\s*$/.test(filename)) {
    $(".file-upload").removeClass('active');
    $("#noFile").text("No file chosen...");
  }
  else {
    $(".file-upload").addClass('active');
    $("#noFile").text(filename.replace("C:\\fakepath\\", ""));
  }
});

});
});
</script>
