<form class="linkform" id="linkform" method="post" autocomplete="off" action="<?php echo $block->getFormAction(); ?>" data-mage-init='{"validation":{}}'>
   <fieldset class="fieldset">
       <legend class="legend"><span><?php echo __('Link your Account') ?></span></legend><br/>
       <div class="field required">
            <label for="link_account" class="label"><span><?php echo __('Curacao Account Number') ?></span></label>
            <div class="control">
                <input id="link_account" type="text" name="curacao_account" class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <label for="link_email" class="label"><span><?php echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" id="link_email" value="" title="<?php echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field required">
            <label for="link_password" class="label"><span><?php echo __('Password') ?></span></label>
            <div class="control">
                <input id="link_password" type="password" name="password" class="input-text" data-validate="{required:true}">
            </div>
        </div>
   </fieldset>
   <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php  echo __('Submit') ?>"><span><?php echo __('Submit') ?></span></button>
        </div>
    </div>
</form>
